//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.APIDTOFacturas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Factura", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTO_Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal FAC_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_NOMBREField;
        
        private System.Nullable<System.DateTime> FAC_FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAC_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CEDULAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CORREOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_DIRECCIONField;
        
        private System.Nullable<decimal> FAC_SUBTOTALField;
        
        private System.Nullable<decimal> FAC_IVAField;
        
        private System.Nullable<decimal> FAC_TOTALField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal FAC_COD {
            get {
                return this.FAC_CODField;
            }
            set {
                if ((this.FAC_CODField.Equals(value) != true)) {
                    this.FAC_CODField = value;
                    this.RaisePropertyChanged("FAC_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EMP_RUC {
            get {
                return this.EMP_RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_RUCField, value) != true)) {
                    this.EMP_RUCField = value;
                    this.RaisePropertyChanged("EMP_RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EMP_NOMBRE {
            get {
                return this.EMP_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_NOMBREField, value) != true)) {
                    this.EMP_NOMBREField = value;
                    this.RaisePropertyChanged("EMP_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> FAC_FECHA {
            get {
                return this.FAC_FECHAField;
            }
            set {
                if ((this.FAC_FECHAField.Equals(value) != true)) {
                    this.FAC_FECHAField = value;
                    this.RaisePropertyChanged("FAC_FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FAC_ESTADO {
            get {
                return this.FAC_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.FAC_ESTADOField, value) != true)) {
                    this.FAC_ESTADOField = value;
                    this.RaisePropertyChanged("FAC_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CLI_CEDULA {
            get {
                return this.CLI_CEDULAField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CEDULAField, value) != true)) {
                    this.CLI_CEDULAField = value;
                    this.RaisePropertyChanged("CLI_CEDULA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CLI_NOMBRE {
            get {
                return this.CLI_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_NOMBREField, value) != true)) {
                    this.CLI_NOMBREField = value;
                    this.RaisePropertyChanged("CLI_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CLI_CORREO {
            get {
                return this.CLI_CORREOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CORREOField, value) != true)) {
                    this.CLI_CORREOField = value;
                    this.RaisePropertyChanged("CLI_CORREO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CLI_DIRECCION {
            get {
                return this.CLI_DIRECCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_DIRECCIONField, value) != true)) {
                    this.CLI_DIRECCIONField = value;
                    this.RaisePropertyChanged("CLI_DIRECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<decimal> FAC_SUBTOTAL {
            get {
                return this.FAC_SUBTOTALField;
            }
            set {
                if ((this.FAC_SUBTOTALField.Equals(value) != true)) {
                    this.FAC_SUBTOTALField = value;
                    this.RaisePropertyChanged("FAC_SUBTOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<decimal> FAC_IVA {
            get {
                return this.FAC_IVAField;
            }
            set {
                if ((this.FAC_IVAField.Equals(value) != true)) {
                    this.FAC_IVAField = value;
                    this.RaisePropertyChanged("FAC_IVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<decimal> FAC_TOTAL {
            get {
                return this.FAC_TOTALField;
            }
            set {
                if ((this.FAC_TOTALField.Equals(value) != true)) {
                    this.FAC_TOTALField = value;
                    this.RaisePropertyChanged("FAC_TOTAL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIDTOFacturas.APIDTOFacturasSoap")]
    public interface APIDTOFacturasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarFacturasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarFacturas", ReplyAction="*")]
        FrontEnd.APIDTOFacturas.MostrarFacturasResponse MostrarFacturas(FrontEnd.APIDTOFacturas.MostrarFacturasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarFacturas", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIDTOFacturas.MostrarFacturasResponse> MostrarFacturasAsync(FrontEnd.APIDTOFacturas.MostrarFacturasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarFacturaPorIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarFacturaPorId", ReplyAction="*")]
        FrontEnd.APIDTOFacturas.MostrarFacturaPorIdResponse MostrarFacturaPorId(FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarFacturaPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIDTOFacturas.MostrarFacturaPorIdResponse> MostrarFacturaPorIdAsync(FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarFacturasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarFacturas", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOFacturas.MostrarFacturasRequestBody Body;
        
        public MostrarFacturasRequest() {
        }
        
        public MostrarFacturasRequest(FrontEnd.APIDTOFacturas.MostrarFacturasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarFacturasRequestBody {
        
        public MostrarFacturasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarFacturasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarFacturasResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOFacturas.MostrarFacturasResponseBody Body;
        
        public MostrarFacturasResponse() {
        }
        
        public MostrarFacturasResponse(FrontEnd.APIDTOFacturas.MostrarFacturasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarFacturasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIDTOFacturas.DTO_Factura[] MostrarFacturasResult;
        
        public MostrarFacturasResponseBody() {
        }
        
        public MostrarFacturasResponseBody(FrontEnd.APIDTOFacturas.DTO_Factura[] MostrarFacturasResult) {
            this.MostrarFacturasResult = MostrarFacturasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarFacturaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarFacturaPorId", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequestBody Body;
        
        public MostrarFacturaPorIdRequest() {
        }
        
        public MostrarFacturaPorIdRequest(FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarFacturaPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal codigo;
        
        public MostrarFacturaPorIdRequestBody() {
        }
        
        public MostrarFacturaPorIdRequestBody(decimal codigo) {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarFacturaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarFacturaPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOFacturas.MostrarFacturaPorIdResponseBody Body;
        
        public MostrarFacturaPorIdResponse() {
        }
        
        public MostrarFacturaPorIdResponse(FrontEnd.APIDTOFacturas.MostrarFacturaPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarFacturaPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIDTOFacturas.DTO_Factura MostrarFacturaPorIdResult;
        
        public MostrarFacturaPorIdResponseBody() {
        }
        
        public MostrarFacturaPorIdResponseBody(FrontEnd.APIDTOFacturas.DTO_Factura MostrarFacturaPorIdResult) {
            this.MostrarFacturaPorIdResult = MostrarFacturaPorIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIDTOFacturasSoapChannel : FrontEnd.APIDTOFacturas.APIDTOFacturasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIDTOFacturasSoapClient : System.ServiceModel.ClientBase<FrontEnd.APIDTOFacturas.APIDTOFacturasSoap>, FrontEnd.APIDTOFacturas.APIDTOFacturasSoap {
        
        public APIDTOFacturasSoapClient() {
        }
        
        public APIDTOFacturasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIDTOFacturasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTOFacturasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTOFacturasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIDTOFacturas.MostrarFacturasResponse FrontEnd.APIDTOFacturas.APIDTOFacturasSoap.MostrarFacturas(FrontEnd.APIDTOFacturas.MostrarFacturasRequest request) {
            return base.Channel.MostrarFacturas(request);
        }
        
        public FrontEnd.APIDTOFacturas.DTO_Factura[] MostrarFacturas() {
            FrontEnd.APIDTOFacturas.MostrarFacturasRequest inValue = new FrontEnd.APIDTOFacturas.MostrarFacturasRequest();
            inValue.Body = new FrontEnd.APIDTOFacturas.MostrarFacturasRequestBody();
            FrontEnd.APIDTOFacturas.MostrarFacturasResponse retVal = ((FrontEnd.APIDTOFacturas.APIDTOFacturasSoap)(this)).MostrarFacturas(inValue);
            return retVal.Body.MostrarFacturasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIDTOFacturas.MostrarFacturasResponse> FrontEnd.APIDTOFacturas.APIDTOFacturasSoap.MostrarFacturasAsync(FrontEnd.APIDTOFacturas.MostrarFacturasRequest request) {
            return base.Channel.MostrarFacturasAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIDTOFacturas.MostrarFacturasResponse> MostrarFacturasAsync() {
            FrontEnd.APIDTOFacturas.MostrarFacturasRequest inValue = new FrontEnd.APIDTOFacturas.MostrarFacturasRequest();
            inValue.Body = new FrontEnd.APIDTOFacturas.MostrarFacturasRequestBody();
            return ((FrontEnd.APIDTOFacturas.APIDTOFacturasSoap)(this)).MostrarFacturasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIDTOFacturas.MostrarFacturaPorIdResponse FrontEnd.APIDTOFacturas.APIDTOFacturasSoap.MostrarFacturaPorId(FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequest request) {
            return base.Channel.MostrarFacturaPorId(request);
        }
        
        public FrontEnd.APIDTOFacturas.DTO_Factura MostrarFacturaPorId(decimal codigo) {
            FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequest inValue = new FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequest();
            inValue.Body = new FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequestBody();
            inValue.Body.codigo = codigo;
            FrontEnd.APIDTOFacturas.MostrarFacturaPorIdResponse retVal = ((FrontEnd.APIDTOFacturas.APIDTOFacturasSoap)(this)).MostrarFacturaPorId(inValue);
            return retVal.Body.MostrarFacturaPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIDTOFacturas.MostrarFacturaPorIdResponse> FrontEnd.APIDTOFacturas.APIDTOFacturasSoap.MostrarFacturaPorIdAsync(FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequest request) {
            return base.Channel.MostrarFacturaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIDTOFacturas.MostrarFacturaPorIdResponse> MostrarFacturaPorIdAsync(decimal codigo) {
            FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequest inValue = new FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequest();
            inValue.Body = new FrontEnd.APIDTOFacturas.MostrarFacturaPorIdRequestBody();
            inValue.Body.codigo = codigo;
            return ((FrontEnd.APIDTOFacturas.APIDTOFacturasSoap)(this)).MostrarFacturaPorIdAsync(inValue);
        }
    }
}
