//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.APIGestionarDetalleFactura {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DETALLE_FACTURA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DETALLE_FACTURA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal ID_DET_FACField;
        
        private decimal FAC_CODField;
        
        private decimal PRD_CODField;
        
        private System.Nullable<decimal> DTF_CANTIDADField;
        
        private System.Nullable<decimal> DTF_PRECIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.FACTURA FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.PRODUCTO PRODUCTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ID_DET_FAC {
            get {
                return this.ID_DET_FACField;
            }
            set {
                if ((this.ID_DET_FACField.Equals(value) != true)) {
                    this.ID_DET_FACField = value;
                    this.RaisePropertyChanged("ID_DET_FAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public decimal FAC_COD {
            get {
                return this.FAC_CODField;
            }
            set {
                if ((this.FAC_CODField.Equals(value) != true)) {
                    this.FAC_CODField = value;
                    this.RaisePropertyChanged("FAC_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> DTF_CANTIDAD {
            get {
                return this.DTF_CANTIDADField;
            }
            set {
                if ((this.DTF_CANTIDADField.Equals(value) != true)) {
                    this.DTF_CANTIDADField = value;
                    this.RaisePropertyChanged("DTF_CANTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> DTF_PRECIO {
            get {
                return this.DTF_PRECIOField;
            }
            set {
                if ((this.DTF_PRECIOField.Equals(value) != true)) {
                    this.DTF_PRECIOField = value;
                    this.RaisePropertyChanged("DTF_PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FrontEnd.APIGestionarDetalleFactura.FACTURA FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FrontEnd.APIGestionarDetalleFactura.PRODUCTO PRODUCTO {
            get {
                return this.PRODUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTOField, value) != true)) {
                    this.PRODUCTOField = value;
                    this.RaisePropertyChanged("PRODUCTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FACTURA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FACTURA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal FAC_CODField;
        
        private decimal ID_EMPField;
        
        private decimal ID_CLIENTEField;
        
        private System.Nullable<System.DateTime> FAC_FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAC_ESTADOField;
        
        private System.Nullable<decimal> FAC_IVAField;
        
        private System.Nullable<decimal> FAC_SUBTOTALField;
        
        private System.Nullable<decimal> FAC_TOTALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.CLIENTE CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA[] DETALLE_FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.EMPRESA EMPRESAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal FAC_COD {
            get {
                return this.FAC_CODField;
            }
            set {
                if ((this.FAC_CODField.Equals(value) != true)) {
                    this.FAC_CODField = value;
                    this.RaisePropertyChanged("FAC_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ID_EMP {
            get {
                return this.ID_EMPField;
            }
            set {
                if ((this.ID_EMPField.Equals(value) != true)) {
                    this.ID_EMPField = value;
                    this.RaisePropertyChanged("ID_EMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal ID_CLIENTE {
            get {
                return this.ID_CLIENTEField;
            }
            set {
                if ((this.ID_CLIENTEField.Equals(value) != true)) {
                    this.ID_CLIENTEField = value;
                    this.RaisePropertyChanged("ID_CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> FAC_FECHA {
            get {
                return this.FAC_FECHAField;
            }
            set {
                if ((this.FAC_FECHAField.Equals(value) != true)) {
                    this.FAC_FECHAField = value;
                    this.RaisePropertyChanged("FAC_FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FAC_ESTADO {
            get {
                return this.FAC_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.FAC_ESTADOField, value) != true)) {
                    this.FAC_ESTADOField = value;
                    this.RaisePropertyChanged("FAC_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> FAC_IVA {
            get {
                return this.FAC_IVAField;
            }
            set {
                if ((this.FAC_IVAField.Equals(value) != true)) {
                    this.FAC_IVAField = value;
                    this.RaisePropertyChanged("FAC_IVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> FAC_SUBTOTAL {
            get {
                return this.FAC_SUBTOTALField;
            }
            set {
                if ((this.FAC_SUBTOTALField.Equals(value) != true)) {
                    this.FAC_SUBTOTALField = value;
                    this.RaisePropertyChanged("FAC_SUBTOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> FAC_TOTAL {
            get {
                return this.FAC_TOTALField;
            }
            set {
                if ((this.FAC_TOTALField.Equals(value) != true)) {
                    this.FAC_TOTALField = value;
                    this.RaisePropertyChanged("FAC_TOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public FrontEnd.APIGestionarDetalleFactura.CLIENTE CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA[] DETALLE_FACTURA {
            get {
                return this.DETALLE_FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLE_FACTURAField, value) != true)) {
                    this.DETALLE_FACTURAField = value;
                    this.RaisePropertyChanged("DETALLE_FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public FrontEnd.APIGestionarDetalleFactura.EMPRESA EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESAField, value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PRODUCTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PRODUCTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal PRD_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRD_DESCRIPCIONField;
        
        private System.Nullable<decimal> PRD_PRECIOField;
        
        private System.Nullable<decimal> PRD_STOCKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA[] DETALLE_FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.IMAGEN[] IMAGENField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PRD_DESCRIPCION {
            get {
                return this.PRD_DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.PRD_DESCRIPCIONField, value) != true)) {
                    this.PRD_DESCRIPCIONField = value;
                    this.RaisePropertyChanged("PRD_DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> PRD_PRECIO {
            get {
                return this.PRD_PRECIOField;
            }
            set {
                if ((this.PRD_PRECIOField.Equals(value) != true)) {
                    this.PRD_PRECIOField = value;
                    this.RaisePropertyChanged("PRD_PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> PRD_STOCK {
            get {
                return this.PRD_STOCKField;
            }
            set {
                if ((this.PRD_STOCKField.Equals(value) != true)) {
                    this.PRD_STOCKField = value;
                    this.RaisePropertyChanged("PRD_STOCK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA[] DETALLE_FACTURA {
            get {
                return this.DETALLE_FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLE_FACTURAField, value) != true)) {
                    this.DETALLE_FACTURAField = value;
                    this.RaisePropertyChanged("DETALLE_FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FrontEnd.APIGestionarDetalleFactura.IMAGEN[] IMAGEN {
            get {
                return this.IMAGENField;
            }
            set {
                if ((object.ReferenceEquals(this.IMAGENField, value) != true)) {
                    this.IMAGENField = value;
                    this.RaisePropertyChanged("IMAGEN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLIENTE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CLIENTE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal ID_CLIENTEField;
        
        private decimal US_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CEDULAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_TELEFONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CORREOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_DIRECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.USUARIO USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.FACTURA[] FACTURAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ID_CLIENTE {
            get {
                return this.ID_CLIENTEField;
            }
            set {
                if ((this.ID_CLIENTEField.Equals(value) != true)) {
                    this.ID_CLIENTEField = value;
                    this.RaisePropertyChanged("ID_CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal US_COD {
            get {
                return this.US_CODField;
            }
            set {
                if ((this.US_CODField.Equals(value) != true)) {
                    this.US_CODField = value;
                    this.RaisePropertyChanged("US_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CLI_CEDULA {
            get {
                return this.CLI_CEDULAField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CEDULAField, value) != true)) {
                    this.CLI_CEDULAField = value;
                    this.RaisePropertyChanged("CLI_CEDULA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CLI_NOMBRE {
            get {
                return this.CLI_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_NOMBREField, value) != true)) {
                    this.CLI_NOMBREField = value;
                    this.RaisePropertyChanged("CLI_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CLI_TELEFONO {
            get {
                return this.CLI_TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_TELEFONOField, value) != true)) {
                    this.CLI_TELEFONOField = value;
                    this.RaisePropertyChanged("CLI_TELEFONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CLI_CORREO {
            get {
                return this.CLI_CORREOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CORREOField, value) != true)) {
                    this.CLI_CORREOField = value;
                    this.RaisePropertyChanged("CLI_CORREO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CLI_DIRECCION {
            get {
                return this.CLI_DIRECCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_DIRECCIONField, value) != true)) {
                    this.CLI_DIRECCIONField = value;
                    this.RaisePropertyChanged("CLI_DIRECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public FrontEnd.APIGestionarDetalleFactura.USUARIO USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public FrontEnd.APIGestionarDetalleFactura.FACTURA[] FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMPRESA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EMPRESA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal ID_EMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_MISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_VISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_TELFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.FACTURA[] FACTURAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ID_EMP {
            get {
                return this.ID_EMPField;
            }
            set {
                if ((this.ID_EMPField.Equals(value) != true)) {
                    this.ID_EMPField = value;
                    this.RaisePropertyChanged("ID_EMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EMP_RUC {
            get {
                return this.EMP_RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_RUCField, value) != true)) {
                    this.EMP_RUCField = value;
                    this.RaisePropertyChanged("EMP_RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EMP_NOMBRE {
            get {
                return this.EMP_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_NOMBREField, value) != true)) {
                    this.EMP_NOMBREField = value;
                    this.RaisePropertyChanged("EMP_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EMP_MISION {
            get {
                return this.EMP_MISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_MISIONField, value) != true)) {
                    this.EMP_MISIONField = value;
                    this.RaisePropertyChanged("EMP_MISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EMP_VISION {
            get {
                return this.EMP_VISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_VISIONField, value) != true)) {
                    this.EMP_VISIONField = value;
                    this.RaisePropertyChanged("EMP_VISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EMP_TELF {
            get {
                return this.EMP_TELFField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_TELFField, value) != true)) {
                    this.EMP_TELFField = value;
                    this.RaisePropertyChanged("EMP_TELF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FrontEnd.APIGestionarDetalleFactura.FACTURA[] FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal US_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_PASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_ROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.CLIENTE[] CLIENTEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal US_COD {
            get {
                return this.US_CODField;
            }
            set {
                if ((this.US_CODField.Equals(value) != true)) {
                    this.US_CODField = value;
                    this.RaisePropertyChanged("US_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string US_USUARIO {
            get {
                return this.US_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.US_USUARIOField, value) != true)) {
                    this.US_USUARIOField = value;
                    this.RaisePropertyChanged("US_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string US_PASS {
            get {
                return this.US_PASSField;
            }
            set {
                if ((object.ReferenceEquals(this.US_PASSField, value) != true)) {
                    this.US_PASSField = value;
                    this.RaisePropertyChanged("US_PASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string US_ROL {
            get {
                return this.US_ROLField;
            }
            set {
                if ((object.ReferenceEquals(this.US_ROLField, value) != true)) {
                    this.US_ROLField = value;
                    this.RaisePropertyChanged("US_ROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public FrontEnd.APIGestionarDetalleFactura.CLIENTE[] CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IMAGEN", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class IMAGEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal IMG_IDField;
        
        private decimal PRD_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarDetalleFactura.PRODUCTO PRODUCTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal IMG_ID {
            get {
                return this.IMG_IDField;
            }
            set {
                if ((this.IMG_IDField.Equals(value) != true)) {
                    this.IMG_IDField = value;
                    this.RaisePropertyChanged("IMG_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMG_URL {
            get {
                return this.IMG_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_URLField, value) != true)) {
                    this.IMG_URLField = value;
                    this.RaisePropertyChanged("IMG_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public FrontEnd.APIGestionarDetalleFactura.PRODUCTO PRODUCTO {
            get {
                return this.PRODUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTOField, value) != true)) {
                    this.PRODUCTOField = value;
                    this.RaisePropertyChanged("PRODUCTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap")]
    public interface APIGestionarDetalleFacturaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SeleccionarDetallesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarDetalles", ReplyAction="*")]
        FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesResponse SeleccionarDetalles(FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarDetalles", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesResponse> SeleccionarDetallesAsync(FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento seleccionarDetallesPorIDResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seleccionarDetallesPorID", ReplyAction="*")]
        FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDResponse seleccionarDetallesPorID(FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seleccionarDetallesPorID", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDResponse> seleccionarDetallesPorIDAsync(FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento proInsertado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDetalleFac", ReplyAction="*")]
        FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacResponse insertarDetalleFac(FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDetalleFac", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacResponse> insertarDetalleFacAsync(FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento proActualizado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleFac", ReplyAction="*")]
        FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacResponse actualizarDetalleFac(FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleFac", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacResponse> actualizarDetalleFacAsync(FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleFac", ReplyAction="*")]
        bool eliminarDetalleFac(decimal id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleFac", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> eliminarDetalleFacAsync(decimal id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarDetallesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarDetalles", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequestBody Body;
        
        public SeleccionarDetallesRequest() {
        }
        
        public SeleccionarDetallesRequest(FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SeleccionarDetallesRequestBody {
        
        public SeleccionarDetallesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarDetallesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarDetallesResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesResponseBody Body;
        
        public SeleccionarDetallesResponse() {
        }
        
        public SeleccionarDetallesResponse(FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarDetallesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA[] SeleccionarDetallesResult;
        
        public SeleccionarDetallesResponseBody() {
        }
        
        public SeleccionarDetallesResponseBody(FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA[] SeleccionarDetallesResult) {
            this.SeleccionarDetallesResult = SeleccionarDetallesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seleccionarDetallesPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seleccionarDetallesPorID", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequestBody Body;
        
        public seleccionarDetallesPorIDRequest() {
        }
        
        public seleccionarDetallesPorIDRequest(FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seleccionarDetallesPorIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal id;
        
        public seleccionarDetallesPorIDRequestBody() {
        }
        
        public seleccionarDetallesPorIDRequestBody(decimal id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seleccionarDetallesPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seleccionarDetallesPorIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDResponseBody Body;
        
        public seleccionarDetallesPorIDResponse() {
        }
        
        public seleccionarDetallesPorIDResponse(FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seleccionarDetallesPorIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA seleccionarDetallesPorIDResult;
        
        public seleccionarDetallesPorIDResponseBody() {
        }
        
        public seleccionarDetallesPorIDResponseBody(FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA seleccionarDetallesPorIDResult) {
            this.seleccionarDetallesPorIDResult = seleccionarDetallesPorIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDetalleFacRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDetalleFac", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequestBody Body;
        
        public insertarDetalleFacRequest() {
        }
        
        public insertarDetalleFacRequest(FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarDetalleFacRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA proInsertado;
        
        public insertarDetalleFacRequestBody() {
        }
        
        public insertarDetalleFacRequestBody(FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA proInsertado) {
            this.proInsertado = proInsertado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDetalleFacResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDetalleFacResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacResponseBody Body;
        
        public insertarDetalleFacResponse() {
        }
        
        public insertarDetalleFacResponse(FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarDetalleFacResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal insertarDetalleFacResult;
        
        public insertarDetalleFacResponseBody() {
        }
        
        public insertarDetalleFacResponseBody(decimal insertarDetalleFacResult) {
            this.insertarDetalleFacResult = insertarDetalleFacResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarDetalleFacRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarDetalleFac", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequestBody Body;
        
        public actualizarDetalleFacRequest() {
        }
        
        public actualizarDetalleFacRequest(FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarDetalleFacRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA proActualizado;
        
        public actualizarDetalleFacRequestBody() {
        }
        
        public actualizarDetalleFacRequestBody(FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA proActualizado) {
            this.proActualizado = proActualizado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarDetalleFacResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarDetalleFacResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacResponseBody Body;
        
        public actualizarDetalleFacResponse() {
        }
        
        public actualizarDetalleFacResponse(FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarDetalleFacResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool actualizarDetalleFacResult;
        
        public actualizarDetalleFacResponseBody() {
        }
        
        public actualizarDetalleFacResponseBody(bool actualizarDetalleFacResult) {
            this.actualizarDetalleFacResult = actualizarDetalleFacResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIGestionarDetalleFacturaSoapChannel : FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIGestionarDetalleFacturaSoapClient : System.ServiceModel.ClientBase<FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap>, FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap {
        
        public APIGestionarDetalleFacturaSoapClient() {
        }
        
        public APIGestionarDetalleFacturaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIGestionarDetalleFacturaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIGestionarDetalleFacturaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIGestionarDetalleFacturaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesResponse FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap.SeleccionarDetalles(FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequest request) {
            return base.Channel.SeleccionarDetalles(request);
        }
        
        public FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA[] SeleccionarDetalles() {
            FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequest inValue = new FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequest();
            inValue.Body = new FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequestBody();
            FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesResponse retVal = ((FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap)(this)).SeleccionarDetalles(inValue);
            return retVal.Body.SeleccionarDetallesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesResponse> FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap.SeleccionarDetallesAsync(FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequest request) {
            return base.Channel.SeleccionarDetallesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesResponse> SeleccionarDetallesAsync() {
            FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequest inValue = new FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequest();
            inValue.Body = new FrontEnd.APIGestionarDetalleFactura.SeleccionarDetallesRequestBody();
            return ((FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap)(this)).SeleccionarDetallesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDResponse FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap.seleccionarDetallesPorID(FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequest request) {
            return base.Channel.seleccionarDetallesPorID(request);
        }
        
        public FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA seleccionarDetallesPorID(decimal id) {
            FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequest inValue = new FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequest();
            inValue.Body = new FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequestBody();
            inValue.Body.id = id;
            FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDResponse retVal = ((FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap)(this)).seleccionarDetallesPorID(inValue);
            return retVal.Body.seleccionarDetallesPorIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDResponse> FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap.seleccionarDetallesPorIDAsync(FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequest request) {
            return base.Channel.seleccionarDetallesPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDResponse> seleccionarDetallesPorIDAsync(decimal id) {
            FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequest inValue = new FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequest();
            inValue.Body = new FrontEnd.APIGestionarDetalleFactura.seleccionarDetallesPorIDRequestBody();
            inValue.Body.id = id;
            return ((FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap)(this)).seleccionarDetallesPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacResponse FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap.insertarDetalleFac(FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequest request) {
            return base.Channel.insertarDetalleFac(request);
        }
        
        public decimal insertarDetalleFac(FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA proInsertado) {
            FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequest inValue = new FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequest();
            inValue.Body = new FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequestBody();
            inValue.Body.proInsertado = proInsertado;
            FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacResponse retVal = ((FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap)(this)).insertarDetalleFac(inValue);
            return retVal.Body.insertarDetalleFacResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacResponse> FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap.insertarDetalleFacAsync(FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequest request) {
            return base.Channel.insertarDetalleFacAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacResponse> insertarDetalleFacAsync(FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA proInsertado) {
            FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequest inValue = new FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequest();
            inValue.Body = new FrontEnd.APIGestionarDetalleFactura.insertarDetalleFacRequestBody();
            inValue.Body.proInsertado = proInsertado;
            return ((FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap)(this)).insertarDetalleFacAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacResponse FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap.actualizarDetalleFac(FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequest request) {
            return base.Channel.actualizarDetalleFac(request);
        }
        
        public bool actualizarDetalleFac(FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA proActualizado) {
            FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequest inValue = new FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequest();
            inValue.Body = new FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequestBody();
            inValue.Body.proActualizado = proActualizado;
            FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacResponse retVal = ((FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap)(this)).actualizarDetalleFac(inValue);
            return retVal.Body.actualizarDetalleFacResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacResponse> FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap.actualizarDetalleFacAsync(FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequest request) {
            return base.Channel.actualizarDetalleFacAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacResponse> actualizarDetalleFacAsync(FrontEnd.APIGestionarDetalleFactura.DETALLE_FACTURA proActualizado) {
            FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequest inValue = new FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequest();
            inValue.Body = new FrontEnd.APIGestionarDetalleFactura.actualizarDetalleFacRequestBody();
            inValue.Body.proActualizado = proActualizado;
            return ((FrontEnd.APIGestionarDetalleFactura.APIGestionarDetalleFacturaSoap)(this)).actualizarDetalleFacAsync(inValue);
        }
        
        public bool eliminarDetalleFac(decimal id) {
            return base.Channel.eliminarDetalleFac(id);
        }
        
        public System.Threading.Tasks.Task<bool> eliminarDetalleFacAsync(decimal id) {
            return base.Channel.eliminarDetalleFacAsync(id);
        }
    }
}
