//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.APIDTOUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTO_Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal US_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_PASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_ROLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal US_COD {
            get {
                return this.US_CODField;
            }
            set {
                if ((this.US_CODField.Equals(value) != true)) {
                    this.US_CODField = value;
                    this.RaisePropertyChanged("US_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string US_USUARIO {
            get {
                return this.US_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.US_USUARIOField, value) != true)) {
                    this.US_USUARIOField = value;
                    this.RaisePropertyChanged("US_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string US_PASS {
            get {
                return this.US_PASSField;
            }
            set {
                if ((object.ReferenceEquals(this.US_PASSField, value) != true)) {
                    this.US_PASSField = value;
                    this.RaisePropertyChanged("US_PASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string US_ROL {
            get {
                return this.US_ROLField;
            }
            set {
                if ((object.ReferenceEquals(this.US_ROLField, value) != true)) {
                    this.US_ROLField = value;
                    this.RaisePropertyChanged("US_ROL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIDTOUsuarios.APIDTOUsuariosSoap")]
    public interface APIDTOUsuariosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarUsuariosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarUsuarios", ReplyAction="*")]
        FrontEnd.APIDTOUsuarios.MostrarUsuariosResponse MostrarUsuarios(FrontEnd.APIDTOUsuarios.MostrarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIDTOUsuarios.MostrarUsuariosResponse> MostrarUsuariosAsync(FrontEnd.APIDTOUsuarios.MostrarUsuariosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOUsuarios.MostrarUsuariosRequestBody Body;
        
        public MostrarUsuariosRequest() {
        }
        
        public MostrarUsuariosRequest(FrontEnd.APIDTOUsuarios.MostrarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarUsuariosRequestBody {
        
        public MostrarUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOUsuarios.MostrarUsuariosResponseBody Body;
        
        public MostrarUsuariosResponse() {
        }
        
        public MostrarUsuariosResponse(FrontEnd.APIDTOUsuarios.MostrarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIDTOUsuarios.DTO_Usuario[] MostrarUsuariosResult;
        
        public MostrarUsuariosResponseBody() {
        }
        
        public MostrarUsuariosResponseBody(FrontEnd.APIDTOUsuarios.DTO_Usuario[] MostrarUsuariosResult) {
            this.MostrarUsuariosResult = MostrarUsuariosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIDTOUsuariosSoapChannel : FrontEnd.APIDTOUsuarios.APIDTOUsuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIDTOUsuariosSoapClient : System.ServiceModel.ClientBase<FrontEnd.APIDTOUsuarios.APIDTOUsuariosSoap>, FrontEnd.APIDTOUsuarios.APIDTOUsuariosSoap {
        
        public APIDTOUsuariosSoapClient() {
        }
        
        public APIDTOUsuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIDTOUsuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTOUsuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTOUsuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIDTOUsuarios.MostrarUsuariosResponse FrontEnd.APIDTOUsuarios.APIDTOUsuariosSoap.MostrarUsuarios(FrontEnd.APIDTOUsuarios.MostrarUsuariosRequest request) {
            return base.Channel.MostrarUsuarios(request);
        }
        
        public FrontEnd.APIDTOUsuarios.DTO_Usuario[] MostrarUsuarios() {
            FrontEnd.APIDTOUsuarios.MostrarUsuariosRequest inValue = new FrontEnd.APIDTOUsuarios.MostrarUsuariosRequest();
            inValue.Body = new FrontEnd.APIDTOUsuarios.MostrarUsuariosRequestBody();
            FrontEnd.APIDTOUsuarios.MostrarUsuariosResponse retVal = ((FrontEnd.APIDTOUsuarios.APIDTOUsuariosSoap)(this)).MostrarUsuarios(inValue);
            return retVal.Body.MostrarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIDTOUsuarios.MostrarUsuariosResponse> FrontEnd.APIDTOUsuarios.APIDTOUsuariosSoap.MostrarUsuariosAsync(FrontEnd.APIDTOUsuarios.MostrarUsuariosRequest request) {
            return base.Channel.MostrarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIDTOUsuarios.MostrarUsuariosResponse> MostrarUsuariosAsync() {
            FrontEnd.APIDTOUsuarios.MostrarUsuariosRequest inValue = new FrontEnd.APIDTOUsuarios.MostrarUsuariosRequest();
            inValue.Body = new FrontEnd.APIDTOUsuarios.MostrarUsuariosRequestBody();
            return ((FrontEnd.APIDTOUsuarios.APIDTOUsuariosSoap)(this)).MostrarUsuariosAsync(inValue);
        }
    }
}
