//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.APIGestionarUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal US_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_PASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_ROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.CLIENTE[] CLIENTEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal US_COD {
            get {
                return this.US_CODField;
            }
            set {
                if ((this.US_CODField.Equals(value) != true)) {
                    this.US_CODField = value;
                    this.RaisePropertyChanged("US_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string US_USUARIO {
            get {
                return this.US_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.US_USUARIOField, value) != true)) {
                    this.US_USUARIOField = value;
                    this.RaisePropertyChanged("US_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string US_PASS {
            get {
                return this.US_PASSField;
            }
            set {
                if ((object.ReferenceEquals(this.US_PASSField, value) != true)) {
                    this.US_PASSField = value;
                    this.RaisePropertyChanged("US_PASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string US_ROL {
            get {
                return this.US_ROLField;
            }
            set {
                if ((object.ReferenceEquals(this.US_ROLField, value) != true)) {
                    this.US_ROLField = value;
                    this.RaisePropertyChanged("US_ROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public FrontEnd.APIGestionarUsuarios.CLIENTE[] CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLIENTE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CLIENTE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal ID_CLIENTEField;
        
        private decimal US_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CEDULAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_TELEFONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CORREOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_DIRECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.USUARIO USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.FACTURA[] FACTURAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ID_CLIENTE {
            get {
                return this.ID_CLIENTEField;
            }
            set {
                if ((this.ID_CLIENTEField.Equals(value) != true)) {
                    this.ID_CLIENTEField = value;
                    this.RaisePropertyChanged("ID_CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal US_COD {
            get {
                return this.US_CODField;
            }
            set {
                if ((this.US_CODField.Equals(value) != true)) {
                    this.US_CODField = value;
                    this.RaisePropertyChanged("US_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CLI_CEDULA {
            get {
                return this.CLI_CEDULAField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CEDULAField, value) != true)) {
                    this.CLI_CEDULAField = value;
                    this.RaisePropertyChanged("CLI_CEDULA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CLI_NOMBRE {
            get {
                return this.CLI_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_NOMBREField, value) != true)) {
                    this.CLI_NOMBREField = value;
                    this.RaisePropertyChanged("CLI_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CLI_TELEFONO {
            get {
                return this.CLI_TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_TELEFONOField, value) != true)) {
                    this.CLI_TELEFONOField = value;
                    this.RaisePropertyChanged("CLI_TELEFONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CLI_CORREO {
            get {
                return this.CLI_CORREOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CORREOField, value) != true)) {
                    this.CLI_CORREOField = value;
                    this.RaisePropertyChanged("CLI_CORREO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CLI_DIRECCION {
            get {
                return this.CLI_DIRECCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_DIRECCIONField, value) != true)) {
                    this.CLI_DIRECCIONField = value;
                    this.RaisePropertyChanged("CLI_DIRECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public FrontEnd.APIGestionarUsuarios.USUARIO USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public FrontEnd.APIGestionarUsuarios.FACTURA[] FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FACTURA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FACTURA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal FAC_CODField;
        
        private decimal ID_EMPField;
        
        private decimal ID_CLIENTEField;
        
        private System.Nullable<System.DateTime> FAC_FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAC_ESTADOField;
        
        private System.Nullable<decimal> FAC_IVAField;
        
        private System.Nullable<decimal> FAC_SUBTOTALField;
        
        private System.Nullable<decimal> FAC_TOTALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.CLIENTE CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.DETALLE_FACTURA[] DETALLE_FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.EMPRESA EMPRESAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal FAC_COD {
            get {
                return this.FAC_CODField;
            }
            set {
                if ((this.FAC_CODField.Equals(value) != true)) {
                    this.FAC_CODField = value;
                    this.RaisePropertyChanged("FAC_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ID_EMP {
            get {
                return this.ID_EMPField;
            }
            set {
                if ((this.ID_EMPField.Equals(value) != true)) {
                    this.ID_EMPField = value;
                    this.RaisePropertyChanged("ID_EMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal ID_CLIENTE {
            get {
                return this.ID_CLIENTEField;
            }
            set {
                if ((this.ID_CLIENTEField.Equals(value) != true)) {
                    this.ID_CLIENTEField = value;
                    this.RaisePropertyChanged("ID_CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> FAC_FECHA {
            get {
                return this.FAC_FECHAField;
            }
            set {
                if ((this.FAC_FECHAField.Equals(value) != true)) {
                    this.FAC_FECHAField = value;
                    this.RaisePropertyChanged("FAC_FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FAC_ESTADO {
            get {
                return this.FAC_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.FAC_ESTADOField, value) != true)) {
                    this.FAC_ESTADOField = value;
                    this.RaisePropertyChanged("FAC_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> FAC_IVA {
            get {
                return this.FAC_IVAField;
            }
            set {
                if ((this.FAC_IVAField.Equals(value) != true)) {
                    this.FAC_IVAField = value;
                    this.RaisePropertyChanged("FAC_IVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> FAC_SUBTOTAL {
            get {
                return this.FAC_SUBTOTALField;
            }
            set {
                if ((this.FAC_SUBTOTALField.Equals(value) != true)) {
                    this.FAC_SUBTOTALField = value;
                    this.RaisePropertyChanged("FAC_SUBTOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> FAC_TOTAL {
            get {
                return this.FAC_TOTALField;
            }
            set {
                if ((this.FAC_TOTALField.Equals(value) != true)) {
                    this.FAC_TOTALField = value;
                    this.RaisePropertyChanged("FAC_TOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public FrontEnd.APIGestionarUsuarios.CLIENTE CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public FrontEnd.APIGestionarUsuarios.DETALLE_FACTURA[] DETALLE_FACTURA {
            get {
                return this.DETALLE_FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLE_FACTURAField, value) != true)) {
                    this.DETALLE_FACTURAField = value;
                    this.RaisePropertyChanged("DETALLE_FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public FrontEnd.APIGestionarUsuarios.EMPRESA EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESAField, value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMPRESA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EMPRESA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal ID_EMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_MISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_VISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_TELFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.FACTURA[] FACTURAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ID_EMP {
            get {
                return this.ID_EMPField;
            }
            set {
                if ((this.ID_EMPField.Equals(value) != true)) {
                    this.ID_EMPField = value;
                    this.RaisePropertyChanged("ID_EMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EMP_RUC {
            get {
                return this.EMP_RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_RUCField, value) != true)) {
                    this.EMP_RUCField = value;
                    this.RaisePropertyChanged("EMP_RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EMP_NOMBRE {
            get {
                return this.EMP_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_NOMBREField, value) != true)) {
                    this.EMP_NOMBREField = value;
                    this.RaisePropertyChanged("EMP_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EMP_MISION {
            get {
                return this.EMP_MISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_MISIONField, value) != true)) {
                    this.EMP_MISIONField = value;
                    this.RaisePropertyChanged("EMP_MISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EMP_VISION {
            get {
                return this.EMP_VISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_VISIONField, value) != true)) {
                    this.EMP_VISIONField = value;
                    this.RaisePropertyChanged("EMP_VISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EMP_TELF {
            get {
                return this.EMP_TELFField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_TELFField, value) != true)) {
                    this.EMP_TELFField = value;
                    this.RaisePropertyChanged("EMP_TELF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FrontEnd.APIGestionarUsuarios.FACTURA[] FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DETALLE_FACTURA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DETALLE_FACTURA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal ID_DET_FACField;
        
        private decimal FAC_CODField;
        
        private decimal PRD_CODField;
        
        private System.Nullable<decimal> DTF_CANTIDADField;
        
        private System.Nullable<decimal> DTF_PRECIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.FACTURA FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.PRODUCTO PRODUCTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ID_DET_FAC {
            get {
                return this.ID_DET_FACField;
            }
            set {
                if ((this.ID_DET_FACField.Equals(value) != true)) {
                    this.ID_DET_FACField = value;
                    this.RaisePropertyChanged("ID_DET_FAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public decimal FAC_COD {
            get {
                return this.FAC_CODField;
            }
            set {
                if ((this.FAC_CODField.Equals(value) != true)) {
                    this.FAC_CODField = value;
                    this.RaisePropertyChanged("FAC_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> DTF_CANTIDAD {
            get {
                return this.DTF_CANTIDADField;
            }
            set {
                if ((this.DTF_CANTIDADField.Equals(value) != true)) {
                    this.DTF_CANTIDADField = value;
                    this.RaisePropertyChanged("DTF_CANTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> DTF_PRECIO {
            get {
                return this.DTF_PRECIOField;
            }
            set {
                if ((this.DTF_PRECIOField.Equals(value) != true)) {
                    this.DTF_PRECIOField = value;
                    this.RaisePropertyChanged("DTF_PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FrontEnd.APIGestionarUsuarios.FACTURA FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FrontEnd.APIGestionarUsuarios.PRODUCTO PRODUCTO {
            get {
                return this.PRODUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTOField, value) != true)) {
                    this.PRODUCTOField = value;
                    this.RaisePropertyChanged("PRODUCTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PRODUCTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PRODUCTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal PRD_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRD_DESCRIPCIONField;
        
        private System.Nullable<decimal> PRD_PRECIOField;
        
        private System.Nullable<decimal> PRD_STOCKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.DETALLE_FACTURA[] DETALLE_FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.IMAGEN[] IMAGENField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PRD_DESCRIPCION {
            get {
                return this.PRD_DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.PRD_DESCRIPCIONField, value) != true)) {
                    this.PRD_DESCRIPCIONField = value;
                    this.RaisePropertyChanged("PRD_DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> PRD_PRECIO {
            get {
                return this.PRD_PRECIOField;
            }
            set {
                if ((this.PRD_PRECIOField.Equals(value) != true)) {
                    this.PRD_PRECIOField = value;
                    this.RaisePropertyChanged("PRD_PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> PRD_STOCK {
            get {
                return this.PRD_STOCKField;
            }
            set {
                if ((this.PRD_STOCKField.Equals(value) != true)) {
                    this.PRD_STOCKField = value;
                    this.RaisePropertyChanged("PRD_STOCK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public FrontEnd.APIGestionarUsuarios.DETALLE_FACTURA[] DETALLE_FACTURA {
            get {
                return this.DETALLE_FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLE_FACTURAField, value) != true)) {
                    this.DETALLE_FACTURAField = value;
                    this.RaisePropertyChanged("DETALLE_FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FrontEnd.APIGestionarUsuarios.IMAGEN[] IMAGEN {
            get {
                return this.IMAGENField;
            }
            set {
                if ((object.ReferenceEquals(this.IMAGENField, value) != true)) {
                    this.IMAGENField = value;
                    this.RaisePropertyChanged("IMAGEN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IMAGEN", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class IMAGEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal IMG_IDField;
        
        private decimal PRD_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarUsuarios.PRODUCTO PRODUCTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal IMG_ID {
            get {
                return this.IMG_IDField;
            }
            set {
                if ((this.IMG_IDField.Equals(value) != true)) {
                    this.IMG_IDField = value;
                    this.RaisePropertyChanged("IMG_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMG_URL {
            get {
                return this.IMG_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_URLField, value) != true)) {
                    this.IMG_URLField = value;
                    this.RaisePropertyChanged("IMG_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public FrontEnd.APIGestionarUsuarios.PRODUCTO PRODUCTO {
            get {
                return this.PRODUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTOField, value) != true)) {
                    this.PRODUCTOField = value;
                    this.RaisePropertyChanged("PRODUCTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIGestionarUsuarios.APIGestionarUsuariosSoap")]
    public interface APIGestionarUsuariosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SeleccionarUsuariosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarUsuarios", ReplyAction="*")]
        FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosResponse SeleccionarUsuarios(FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosResponse> SeleccionarUsuariosAsync(FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuarioInsertado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUsuario", ReplyAction="*")]
        FrontEnd.APIGestionarUsuarios.insertarUsuarioResponse insertarUsuario(FrontEnd.APIGestionarUsuarios.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarUsuarios.insertarUsuarioResponse> insertarUsuarioAsync(FrontEnd.APIGestionarUsuarios.insertarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuarioActualizado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarUsuario", ReplyAction="*")]
        FrontEnd.APIGestionarUsuarios.actualizarUsuarioResponse actualizarUsuario(FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarUsuarios.actualizarUsuarioResponse> actualizarUsuarioAsync(FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUsuario", ReplyAction="*")]
        bool eliminarUsuario(decimal id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> eliminarUsuarioAsync(decimal id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequestBody Body;
        
        public SeleccionarUsuariosRequest() {
        }
        
        public SeleccionarUsuariosRequest(FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SeleccionarUsuariosRequestBody {
        
        public SeleccionarUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosResponseBody Body;
        
        public SeleccionarUsuariosResponse() {
        }
        
        public SeleccionarUsuariosResponse(FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarUsuarios.USUARIO[] SeleccionarUsuariosResult;
        
        public SeleccionarUsuariosResponseBody() {
        }
        
        public SeleccionarUsuariosResponseBody(FrontEnd.APIGestionarUsuarios.USUARIO[] SeleccionarUsuariosResult) {
            this.SeleccionarUsuariosResult = SeleccionarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarUsuarios.insertarUsuarioRequestBody Body;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(FrontEnd.APIGestionarUsuarios.insertarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarUsuarios.USUARIO usuarioInsertado;
        
        public insertarUsuarioRequestBody() {
        }
        
        public insertarUsuarioRequestBody(FrontEnd.APIGestionarUsuarios.USUARIO usuarioInsertado) {
            this.usuarioInsertado = usuarioInsertado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarUsuarios.insertarUsuarioResponseBody Body;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(FrontEnd.APIGestionarUsuarios.insertarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal insertarUsuarioResult;
        
        public insertarUsuarioResponseBody() {
        }
        
        public insertarUsuarioResponseBody(decimal insertarUsuarioResult) {
            this.insertarUsuarioResult = insertarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequestBody Body;
        
        public actualizarUsuarioRequest() {
        }
        
        public actualizarUsuarioRequest(FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarUsuarios.USUARIO usuarioActualizado;
        
        public actualizarUsuarioRequestBody() {
        }
        
        public actualizarUsuarioRequestBody(FrontEnd.APIGestionarUsuarios.USUARIO usuarioActualizado) {
            this.usuarioActualizado = usuarioActualizado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarUsuarios.actualizarUsuarioResponseBody Body;
        
        public actualizarUsuarioResponse() {
        }
        
        public actualizarUsuarioResponse(FrontEnd.APIGestionarUsuarios.actualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool actualizarUsuarioResult;
        
        public actualizarUsuarioResponseBody() {
        }
        
        public actualizarUsuarioResponseBody(bool actualizarUsuarioResult) {
            this.actualizarUsuarioResult = actualizarUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIGestionarUsuariosSoapChannel : FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIGestionarUsuariosSoapClient : System.ServiceModel.ClientBase<FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap>, FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap {
        
        public APIGestionarUsuariosSoapClient() {
        }
        
        public APIGestionarUsuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIGestionarUsuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIGestionarUsuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIGestionarUsuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosResponse FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap.SeleccionarUsuarios(FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequest request) {
            return base.Channel.SeleccionarUsuarios(request);
        }
        
        public FrontEnd.APIGestionarUsuarios.USUARIO[] SeleccionarUsuarios() {
            FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequest inValue = new FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequest();
            inValue.Body = new FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequestBody();
            FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosResponse retVal = ((FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap)(this)).SeleccionarUsuarios(inValue);
            return retVal.Body.SeleccionarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosResponse> FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap.SeleccionarUsuariosAsync(FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequest request) {
            return base.Channel.SeleccionarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosResponse> SeleccionarUsuariosAsync() {
            FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequest inValue = new FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequest();
            inValue.Body = new FrontEnd.APIGestionarUsuarios.SeleccionarUsuariosRequestBody();
            return ((FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap)(this)).SeleccionarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarUsuarios.insertarUsuarioResponse FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap.insertarUsuario(FrontEnd.APIGestionarUsuarios.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public decimal insertarUsuario(FrontEnd.APIGestionarUsuarios.USUARIO usuarioInsertado) {
            FrontEnd.APIGestionarUsuarios.insertarUsuarioRequest inValue = new FrontEnd.APIGestionarUsuarios.insertarUsuarioRequest();
            inValue.Body = new FrontEnd.APIGestionarUsuarios.insertarUsuarioRequestBody();
            inValue.Body.usuarioInsertado = usuarioInsertado;
            FrontEnd.APIGestionarUsuarios.insertarUsuarioResponse retVal = ((FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap)(this)).insertarUsuario(inValue);
            return retVal.Body.insertarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarUsuarios.insertarUsuarioResponse> FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap.insertarUsuarioAsync(FrontEnd.APIGestionarUsuarios.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarUsuarios.insertarUsuarioResponse> insertarUsuarioAsync(FrontEnd.APIGestionarUsuarios.USUARIO usuarioInsertado) {
            FrontEnd.APIGestionarUsuarios.insertarUsuarioRequest inValue = new FrontEnd.APIGestionarUsuarios.insertarUsuarioRequest();
            inValue.Body = new FrontEnd.APIGestionarUsuarios.insertarUsuarioRequestBody();
            inValue.Body.usuarioInsertado = usuarioInsertado;
            return ((FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap)(this)).insertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarUsuarios.actualizarUsuarioResponse FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap.actualizarUsuario(FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequest request) {
            return base.Channel.actualizarUsuario(request);
        }
        
        public bool actualizarUsuario(FrontEnd.APIGestionarUsuarios.USUARIO usuarioActualizado) {
            FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequest inValue = new FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequest();
            inValue.Body = new FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequestBody();
            inValue.Body.usuarioActualizado = usuarioActualizado;
            FrontEnd.APIGestionarUsuarios.actualizarUsuarioResponse retVal = ((FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap)(this)).actualizarUsuario(inValue);
            return retVal.Body.actualizarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarUsuarios.actualizarUsuarioResponse> FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap.actualizarUsuarioAsync(FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequest request) {
            return base.Channel.actualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarUsuarios.actualizarUsuarioResponse> actualizarUsuarioAsync(FrontEnd.APIGestionarUsuarios.USUARIO usuarioActualizado) {
            FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequest inValue = new FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequest();
            inValue.Body = new FrontEnd.APIGestionarUsuarios.actualizarUsuarioRequestBody();
            inValue.Body.usuarioActualizado = usuarioActualizado;
            return ((FrontEnd.APIGestionarUsuarios.APIGestionarUsuariosSoap)(this)).actualizarUsuarioAsync(inValue);
        }
        
        public bool eliminarUsuario(decimal id) {
            return base.Channel.eliminarUsuario(id);
        }
        
        public System.Threading.Tasks.Task<bool> eliminarUsuarioAsync(decimal id) {
            return base.Channel.eliminarUsuarioAsync(id);
        }
    }
}
