//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Tienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
        }
    
        public int FAC_COD { get; set; }
        public int ID_EMP { get; set; }
        public string CLI_CEDULA { get; set; }
        public Nullable<System.DateTime> FAC_FECHA { get; set; }
        public string FAC_ESTADO { get; set; }
        public Nullable<decimal> FAC_SUBTOTAL { get; set; }
        public Nullable<decimal> FAC_IVA { get; set; }
        public Nullable<decimal> FAC_TOTAL { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
