//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.APIDTODetalleFactura {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Detalle_Factura", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTO_Detalle_Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_DET_FACField;
        
        private int FAC_CODField;
        
        private int PRD_CODField;
        
        private System.Nullable<int> DTF_CANTIDADField;
        
        private System.Nullable<decimal> DTF_PRECIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DTF_ESTADOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_DET_FAC {
            get {
                return this.ID_DET_FACField;
            }
            set {
                if ((this.ID_DET_FACField.Equals(value) != true)) {
                    this.ID_DET_FACField = value;
                    this.RaisePropertyChanged("ID_DET_FAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int FAC_COD {
            get {
                return this.FAC_CODField;
            }
            set {
                if ((this.FAC_CODField.Equals(value) != true)) {
                    this.FAC_CODField = value;
                    this.RaisePropertyChanged("FAC_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> DTF_CANTIDAD {
            get {
                return this.DTF_CANTIDADField;
            }
            set {
                if ((this.DTF_CANTIDADField.Equals(value) != true)) {
                    this.DTF_CANTIDADField = value;
                    this.RaisePropertyChanged("DTF_CANTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> DTF_PRECIO {
            get {
                return this.DTF_PRECIOField;
            }
            set {
                if ((this.DTF_PRECIOField.Equals(value) != true)) {
                    this.DTF_PRECIOField = value;
                    this.RaisePropertyChanged("DTF_PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DTF_ESTADO {
            get {
                return this.DTF_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.DTF_ESTADOField, value) != true)) {
                    this.DTF_ESTADOField = value;
                    this.RaisePropertyChanged("DTF_ESTADO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIDTODetalleFactura.APIDTODetalleFacturaSoap")]
    public interface APIDTODetalleFacturaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarDetallesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarDetalles", ReplyAction="*")]
        FrontEnd.APIDTODetalleFactura.MostrarDetallesResponse MostrarDetalles(FrontEnd.APIDTODetalleFactura.MostrarDetallesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarDetalles", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIDTODetalleFactura.MostrarDetallesResponse> MostrarDetallesAsync(FrontEnd.APIDTODetalleFactura.MostrarDetallesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarDetallesPorIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarDetallesPorId", ReplyAction="*")]
        FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdResponse MostrarDetallesPorId(FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarDetallesPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdResponse> MostrarDetallesPorIdAsync(FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarDetallesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarDetalles", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTODetalleFactura.MostrarDetallesRequestBody Body;
        
        public MostrarDetallesRequest() {
        }
        
        public MostrarDetallesRequest(FrontEnd.APIDTODetalleFactura.MostrarDetallesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarDetallesRequestBody {
        
        public MostrarDetallesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarDetallesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarDetallesResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTODetalleFactura.MostrarDetallesResponseBody Body;
        
        public MostrarDetallesResponse() {
        }
        
        public MostrarDetallesResponse(FrontEnd.APIDTODetalleFactura.MostrarDetallesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarDetallesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIDTODetalleFactura.DTO_Detalle_Factura[] MostrarDetallesResult;
        
        public MostrarDetallesResponseBody() {
        }
        
        public MostrarDetallesResponseBody(FrontEnd.APIDTODetalleFactura.DTO_Detalle_Factura[] MostrarDetallesResult) {
            this.MostrarDetallesResult = MostrarDetallesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarDetallesPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarDetallesPorId", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequestBody Body;
        
        public MostrarDetallesPorIdRequest() {
        }
        
        public MostrarDetallesPorIdRequest(FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarDetallesPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public MostrarDetallesPorIdRequestBody() {
        }
        
        public MostrarDetallesPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarDetallesPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarDetallesPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdResponseBody Body;
        
        public MostrarDetallesPorIdResponse() {
        }
        
        public MostrarDetallesPorIdResponse(FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarDetallesPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIDTODetalleFactura.DTO_Detalle_Factura MostrarDetallesPorIdResult;
        
        public MostrarDetallesPorIdResponseBody() {
        }
        
        public MostrarDetallesPorIdResponseBody(FrontEnd.APIDTODetalleFactura.DTO_Detalle_Factura MostrarDetallesPorIdResult) {
            this.MostrarDetallesPorIdResult = MostrarDetallesPorIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIDTODetalleFacturaSoapChannel : FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIDTODetalleFacturaSoapClient : System.ServiceModel.ClientBase<FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap>, FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap {
        
        public APIDTODetalleFacturaSoapClient() {
        }
        
        public APIDTODetalleFacturaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIDTODetalleFacturaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTODetalleFacturaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTODetalleFacturaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIDTODetalleFactura.MostrarDetallesResponse FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap.MostrarDetalles(FrontEnd.APIDTODetalleFactura.MostrarDetallesRequest request) {
            return base.Channel.MostrarDetalles(request);
        }
        
        public FrontEnd.APIDTODetalleFactura.DTO_Detalle_Factura[] MostrarDetalles() {
            FrontEnd.APIDTODetalleFactura.MostrarDetallesRequest inValue = new FrontEnd.APIDTODetalleFactura.MostrarDetallesRequest();
            inValue.Body = new FrontEnd.APIDTODetalleFactura.MostrarDetallesRequestBody();
            FrontEnd.APIDTODetalleFactura.MostrarDetallesResponse retVal = ((FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap)(this)).MostrarDetalles(inValue);
            return retVal.Body.MostrarDetallesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIDTODetalleFactura.MostrarDetallesResponse> FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap.MostrarDetallesAsync(FrontEnd.APIDTODetalleFactura.MostrarDetallesRequest request) {
            return base.Channel.MostrarDetallesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIDTODetalleFactura.MostrarDetallesResponse> MostrarDetallesAsync() {
            FrontEnd.APIDTODetalleFactura.MostrarDetallesRequest inValue = new FrontEnd.APIDTODetalleFactura.MostrarDetallesRequest();
            inValue.Body = new FrontEnd.APIDTODetalleFactura.MostrarDetallesRequestBody();
            return ((FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap)(this)).MostrarDetallesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdResponse FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap.MostrarDetallesPorId(FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequest request) {
            return base.Channel.MostrarDetallesPorId(request);
        }
        
        public FrontEnd.APIDTODetalleFactura.DTO_Detalle_Factura MostrarDetallesPorId(int id) {
            FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequest inValue = new FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequest();
            inValue.Body = new FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequestBody();
            inValue.Body.id = id;
            FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdResponse retVal = ((FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap)(this)).MostrarDetallesPorId(inValue);
            return retVal.Body.MostrarDetallesPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdResponse> FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap.MostrarDetallesPorIdAsync(FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequest request) {
            return base.Channel.MostrarDetallesPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdResponse> MostrarDetallesPorIdAsync(int id) {
            FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequest inValue = new FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequest();
            inValue.Body = new FrontEnd.APIDTODetalleFactura.MostrarDetallesPorIdRequestBody();
            inValue.Body.id = id;
            return ((FrontEnd.APIDTODetalleFactura.APIDTODetalleFacturaSoap)(this)).MostrarDetallesPorIdAsync(inValue);
        }
    }
}
