//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.APIDTOImagenes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Imagen", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTO_Imagen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IMG_IDField;
        
        private int PRD_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_TIPOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IMG_ID {
            get {
                return this.IMG_IDField;
            }
            set {
                if ((this.IMG_IDField.Equals(value) != true)) {
                    this.IMG_IDField = value;
                    this.RaisePropertyChanged("IMG_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMG_URL {
            get {
                return this.IMG_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_URLField, value) != true)) {
                    this.IMG_URLField = value;
                    this.RaisePropertyChanged("IMG_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IMG_TIPO {
            get {
                return this.IMG_TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_TIPOField, value) != true)) {
                    this.IMG_TIPOField = value;
                    this.RaisePropertyChanged("IMG_TIPO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIDTOImagenes.APIDTOImagenesSoap")]
    public interface APIDTOImagenesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarImagenesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarImagenes", ReplyAction="*")]
        FrontEnd.APIDTOImagenes.MostrarImagenesResponse MostrarImagenes(FrontEnd.APIDTOImagenes.MostrarImagenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarImagenes", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIDTOImagenes.MostrarImagenesResponse> MostrarImagenesAsync(FrontEnd.APIDTOImagenes.MostrarImagenesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarImagenPorIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarImagenPorId", ReplyAction="*")]
        FrontEnd.APIDTOImagenes.MostrarImagenPorIdResponse MostrarImagenPorId(FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarImagenPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIDTOImagenes.MostrarImagenPorIdResponse> MostrarImagenPorIdAsync(FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarImagenesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarImagenes", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOImagenes.MostrarImagenesRequestBody Body;
        
        public MostrarImagenesRequest() {
        }
        
        public MostrarImagenesRequest(FrontEnd.APIDTOImagenes.MostrarImagenesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarImagenesRequestBody {
        
        public MostrarImagenesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarImagenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarImagenesResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOImagenes.MostrarImagenesResponseBody Body;
        
        public MostrarImagenesResponse() {
        }
        
        public MostrarImagenesResponse(FrontEnd.APIDTOImagenes.MostrarImagenesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarImagenesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIDTOImagenes.DTO_Imagen[] MostrarImagenesResult;
        
        public MostrarImagenesResponseBody() {
        }
        
        public MostrarImagenesResponseBody(FrontEnd.APIDTOImagenes.DTO_Imagen[] MostrarImagenesResult) {
            this.MostrarImagenesResult = MostrarImagenesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarImagenPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarImagenPorId", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequestBody Body;
        
        public MostrarImagenPorIdRequest() {
        }
        
        public MostrarImagenPorIdRequest(FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarImagenPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public MostrarImagenPorIdRequestBody() {
        }
        
        public MostrarImagenPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarImagenPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarImagenPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOImagenes.MostrarImagenPorIdResponseBody Body;
        
        public MostrarImagenPorIdResponse() {
        }
        
        public MostrarImagenPorIdResponse(FrontEnd.APIDTOImagenes.MostrarImagenPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarImagenPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIDTOImagenes.DTO_Imagen MostrarImagenPorIdResult;
        
        public MostrarImagenPorIdResponseBody() {
        }
        
        public MostrarImagenPorIdResponseBody(FrontEnd.APIDTOImagenes.DTO_Imagen MostrarImagenPorIdResult) {
            this.MostrarImagenPorIdResult = MostrarImagenPorIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIDTOImagenesSoapChannel : FrontEnd.APIDTOImagenes.APIDTOImagenesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIDTOImagenesSoapClient : System.ServiceModel.ClientBase<FrontEnd.APIDTOImagenes.APIDTOImagenesSoap>, FrontEnd.APIDTOImagenes.APIDTOImagenesSoap {
        
        public APIDTOImagenesSoapClient() {
        }
        
        public APIDTOImagenesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIDTOImagenesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTOImagenesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTOImagenesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIDTOImagenes.MostrarImagenesResponse FrontEnd.APIDTOImagenes.APIDTOImagenesSoap.MostrarImagenes(FrontEnd.APIDTOImagenes.MostrarImagenesRequest request) {
            return base.Channel.MostrarImagenes(request);
        }
        
        public FrontEnd.APIDTOImagenes.DTO_Imagen[] MostrarImagenes() {
            FrontEnd.APIDTOImagenes.MostrarImagenesRequest inValue = new FrontEnd.APIDTOImagenes.MostrarImagenesRequest();
            inValue.Body = new FrontEnd.APIDTOImagenes.MostrarImagenesRequestBody();
            FrontEnd.APIDTOImagenes.MostrarImagenesResponse retVal = ((FrontEnd.APIDTOImagenes.APIDTOImagenesSoap)(this)).MostrarImagenes(inValue);
            return retVal.Body.MostrarImagenesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIDTOImagenes.MostrarImagenesResponse> FrontEnd.APIDTOImagenes.APIDTOImagenesSoap.MostrarImagenesAsync(FrontEnd.APIDTOImagenes.MostrarImagenesRequest request) {
            return base.Channel.MostrarImagenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIDTOImagenes.MostrarImagenesResponse> MostrarImagenesAsync() {
            FrontEnd.APIDTOImagenes.MostrarImagenesRequest inValue = new FrontEnd.APIDTOImagenes.MostrarImagenesRequest();
            inValue.Body = new FrontEnd.APIDTOImagenes.MostrarImagenesRequestBody();
            return ((FrontEnd.APIDTOImagenes.APIDTOImagenesSoap)(this)).MostrarImagenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIDTOImagenes.MostrarImagenPorIdResponse FrontEnd.APIDTOImagenes.APIDTOImagenesSoap.MostrarImagenPorId(FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequest request) {
            return base.Channel.MostrarImagenPorId(request);
        }
        
        public FrontEnd.APIDTOImagenes.DTO_Imagen MostrarImagenPorId(int id) {
            FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequest inValue = new FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequest();
            inValue.Body = new FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequestBody();
            inValue.Body.id = id;
            FrontEnd.APIDTOImagenes.MostrarImagenPorIdResponse retVal = ((FrontEnd.APIDTOImagenes.APIDTOImagenesSoap)(this)).MostrarImagenPorId(inValue);
            return retVal.Body.MostrarImagenPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIDTOImagenes.MostrarImagenPorIdResponse> FrontEnd.APIDTOImagenes.APIDTOImagenesSoap.MostrarImagenPorIdAsync(FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequest request) {
            return base.Channel.MostrarImagenPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIDTOImagenes.MostrarImagenPorIdResponse> MostrarImagenPorIdAsync(int id) {
            FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequest inValue = new FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequest();
            inValue.Body = new FrontEnd.APIDTOImagenes.MostrarImagenPorIdRequestBody();
            inValue.Body.id = id;
            return ((FrontEnd.APIDTOImagenes.APIDTOImagenesSoap)(this)).MostrarImagenPorIdAsync(inValue);
        }
    }
}
