//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.APIDTOProductos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Producto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTO_Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal PRD_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRD_DESCRIPCIONField;
        
        private decimal PRD_PRECIOField;
        
        private decimal PRD_STOCKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PRD_DESCRIPCION {
            get {
                return this.PRD_DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.PRD_DESCRIPCIONField, value) != true)) {
                    this.PRD_DESCRIPCIONField = value;
                    this.RaisePropertyChanged("PRD_DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PRD_PRECIO {
            get {
                return this.PRD_PRECIOField;
            }
            set {
                if ((this.PRD_PRECIOField.Equals(value) != true)) {
                    this.PRD_PRECIOField = value;
                    this.RaisePropertyChanged("PRD_PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PRD_STOCK {
            get {
                return this.PRD_STOCKField;
            }
            set {
                if ((this.PRD_STOCKField.Equals(value) != true)) {
                    this.PRD_STOCKField = value;
                    this.RaisePropertyChanged("PRD_STOCK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IMG_URL {
            get {
                return this.IMG_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_URLField, value) != true)) {
                    this.IMG_URLField = value;
                    this.RaisePropertyChanged("IMG_URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIDTOProductos.APIDTOProductosSoap")]
    public interface APIDTOProductosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarProductosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarProductos", ReplyAction="*")]
        FrontEnd.APIDTOProductos.MostrarProductosResponse MostrarProductos(FrontEnd.APIDTOProductos.MostrarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIDTOProductos.MostrarProductosResponse> MostrarProductosAsync(FrontEnd.APIDTOProductos.MostrarProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarProductoPorIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarProductoPorId", ReplyAction="*")]
        FrontEnd.APIDTOProductos.MostrarProductoPorIdResponse MostrarProductoPorId(FrontEnd.APIDTOProductos.MostrarProductoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarProductoPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIDTOProductos.MostrarProductoPorIdResponse> MostrarProductoPorIdAsync(FrontEnd.APIDTOProductos.MostrarProductoPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarProductos", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOProductos.MostrarProductosRequestBody Body;
        
        public MostrarProductosRequest() {
        }
        
        public MostrarProductosRequest(FrontEnd.APIDTOProductos.MostrarProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarProductosRequestBody {
        
        public MostrarProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOProductos.MostrarProductosResponseBody Body;
        
        public MostrarProductosResponse() {
        }
        
        public MostrarProductosResponse(FrontEnd.APIDTOProductos.MostrarProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIDTOProductos.DTO_Producto[] MostrarProductosResult;
        
        public MostrarProductosResponseBody() {
        }
        
        public MostrarProductosResponseBody(FrontEnd.APIDTOProductos.DTO_Producto[] MostrarProductosResult) {
            this.MostrarProductosResult = MostrarProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarProductoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarProductoPorId", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOProductos.MostrarProductoPorIdRequestBody Body;
        
        public MostrarProductoPorIdRequest() {
        }
        
        public MostrarProductoPorIdRequest(FrontEnd.APIDTOProductos.MostrarProductoPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarProductoPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal id;
        
        public MostrarProductoPorIdRequestBody() {
        }
        
        public MostrarProductoPorIdRequestBody(decimal id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarProductoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarProductoPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOProductos.MostrarProductoPorIdResponseBody Body;
        
        public MostrarProductoPorIdResponse() {
        }
        
        public MostrarProductoPorIdResponse(FrontEnd.APIDTOProductos.MostrarProductoPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarProductoPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIDTOProductos.DTO_Producto MostrarProductoPorIdResult;
        
        public MostrarProductoPorIdResponseBody() {
        }
        
        public MostrarProductoPorIdResponseBody(FrontEnd.APIDTOProductos.DTO_Producto MostrarProductoPorIdResult) {
            this.MostrarProductoPorIdResult = MostrarProductoPorIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIDTOProductosSoapChannel : FrontEnd.APIDTOProductos.APIDTOProductosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIDTOProductosSoapClient : System.ServiceModel.ClientBase<FrontEnd.APIDTOProductos.APIDTOProductosSoap>, FrontEnd.APIDTOProductos.APIDTOProductosSoap {
        
        public APIDTOProductosSoapClient() {
        }
        
        public APIDTOProductosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIDTOProductosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTOProductosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTOProductosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIDTOProductos.MostrarProductosResponse FrontEnd.APIDTOProductos.APIDTOProductosSoap.MostrarProductos(FrontEnd.APIDTOProductos.MostrarProductosRequest request) {
            return base.Channel.MostrarProductos(request);
        }
        
        public FrontEnd.APIDTOProductos.DTO_Producto[] MostrarProductos() {
            FrontEnd.APIDTOProductos.MostrarProductosRequest inValue = new FrontEnd.APIDTOProductos.MostrarProductosRequest();
            inValue.Body = new FrontEnd.APIDTOProductos.MostrarProductosRequestBody();
            FrontEnd.APIDTOProductos.MostrarProductosResponse retVal = ((FrontEnd.APIDTOProductos.APIDTOProductosSoap)(this)).MostrarProductos(inValue);
            return retVal.Body.MostrarProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIDTOProductos.MostrarProductosResponse> FrontEnd.APIDTOProductos.APIDTOProductosSoap.MostrarProductosAsync(FrontEnd.APIDTOProductos.MostrarProductosRequest request) {
            return base.Channel.MostrarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIDTOProductos.MostrarProductosResponse> MostrarProductosAsync() {
            FrontEnd.APIDTOProductos.MostrarProductosRequest inValue = new FrontEnd.APIDTOProductos.MostrarProductosRequest();
            inValue.Body = new FrontEnd.APIDTOProductos.MostrarProductosRequestBody();
            return ((FrontEnd.APIDTOProductos.APIDTOProductosSoap)(this)).MostrarProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIDTOProductos.MostrarProductoPorIdResponse FrontEnd.APIDTOProductos.APIDTOProductosSoap.MostrarProductoPorId(FrontEnd.APIDTOProductos.MostrarProductoPorIdRequest request) {
            return base.Channel.MostrarProductoPorId(request);
        }
        
        public FrontEnd.APIDTOProductos.DTO_Producto MostrarProductoPorId(decimal id) {
            FrontEnd.APIDTOProductos.MostrarProductoPorIdRequest inValue = new FrontEnd.APIDTOProductos.MostrarProductoPorIdRequest();
            inValue.Body = new FrontEnd.APIDTOProductos.MostrarProductoPorIdRequestBody();
            inValue.Body.id = id;
            FrontEnd.APIDTOProductos.MostrarProductoPorIdResponse retVal = ((FrontEnd.APIDTOProductos.APIDTOProductosSoap)(this)).MostrarProductoPorId(inValue);
            return retVal.Body.MostrarProductoPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIDTOProductos.MostrarProductoPorIdResponse> FrontEnd.APIDTOProductos.APIDTOProductosSoap.MostrarProductoPorIdAsync(FrontEnd.APIDTOProductos.MostrarProductoPorIdRequest request) {
            return base.Channel.MostrarProductoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIDTOProductos.MostrarProductoPorIdResponse> MostrarProductoPorIdAsync(decimal id) {
            FrontEnd.APIDTOProductos.MostrarProductoPorIdRequest inValue = new FrontEnd.APIDTOProductos.MostrarProductoPorIdRequest();
            inValue.Body = new FrontEnd.APIDTOProductos.MostrarProductoPorIdRequestBody();
            inValue.Body.id = id;
            return ((FrontEnd.APIDTOProductos.APIDTOProductosSoap)(this)).MostrarProductoPorIdAsync(inValue);
        }
    }
}
