//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.APIDTOEmpresa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMPRESA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EMPRESA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_EMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_MISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_VISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_TELFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.FACTURA[] FACTURAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_EMP {
            get {
                return this.ID_EMPField;
            }
            set {
                if ((this.ID_EMPField.Equals(value) != true)) {
                    this.ID_EMPField = value;
                    this.RaisePropertyChanged("ID_EMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EMP_RUC {
            get {
                return this.EMP_RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_RUCField, value) != true)) {
                    this.EMP_RUCField = value;
                    this.RaisePropertyChanged("EMP_RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EMP_NOMBRE {
            get {
                return this.EMP_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_NOMBREField, value) != true)) {
                    this.EMP_NOMBREField = value;
                    this.RaisePropertyChanged("EMP_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EMP_MISION {
            get {
                return this.EMP_MISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_MISIONField, value) != true)) {
                    this.EMP_MISIONField = value;
                    this.RaisePropertyChanged("EMP_MISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EMP_VISION {
            get {
                return this.EMP_VISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_VISIONField, value) != true)) {
                    this.EMP_VISIONField = value;
                    this.RaisePropertyChanged("EMP_VISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EMP_TELF {
            get {
                return this.EMP_TELFField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_TELFField, value) != true)) {
                    this.EMP_TELFField = value;
                    this.RaisePropertyChanged("EMP_TELF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FrontEnd.APIDTOEmpresa.FACTURA[] FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FACTURA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FACTURA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FAC_CODField;
        
        private int ID_EMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CEDULAField;
        
        private System.Nullable<System.DateTime> FAC_FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAC_ESTADOField;
        
        private System.Nullable<decimal> FAC_SUBTOTALField;
        
        private System.Nullable<decimal> FAC_IVAField;
        
        private System.Nullable<decimal> FAC_TOTALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.CLIENTE CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.DETALLE_FACTURA[] DETALLE_FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.EMPRESA EMPRESAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FAC_COD {
            get {
                return this.FAC_CODField;
            }
            set {
                if ((this.FAC_CODField.Equals(value) != true)) {
                    this.FAC_CODField = value;
                    this.RaisePropertyChanged("FAC_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_EMP {
            get {
                return this.ID_EMPField;
            }
            set {
                if ((this.ID_EMPField.Equals(value) != true)) {
                    this.ID_EMPField = value;
                    this.RaisePropertyChanged("ID_EMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CLI_CEDULA {
            get {
                return this.CLI_CEDULAField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CEDULAField, value) != true)) {
                    this.CLI_CEDULAField = value;
                    this.RaisePropertyChanged("CLI_CEDULA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> FAC_FECHA {
            get {
                return this.FAC_FECHAField;
            }
            set {
                if ((this.FAC_FECHAField.Equals(value) != true)) {
                    this.FAC_FECHAField = value;
                    this.RaisePropertyChanged("FAC_FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FAC_ESTADO {
            get {
                return this.FAC_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.FAC_ESTADOField, value) != true)) {
                    this.FAC_ESTADOField = value;
                    this.RaisePropertyChanged("FAC_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> FAC_SUBTOTAL {
            get {
                return this.FAC_SUBTOTALField;
            }
            set {
                if ((this.FAC_SUBTOTALField.Equals(value) != true)) {
                    this.FAC_SUBTOTALField = value;
                    this.RaisePropertyChanged("FAC_SUBTOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> FAC_IVA {
            get {
                return this.FAC_IVAField;
            }
            set {
                if ((this.FAC_IVAField.Equals(value) != true)) {
                    this.FAC_IVAField = value;
                    this.RaisePropertyChanged("FAC_IVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> FAC_TOTAL {
            get {
                return this.FAC_TOTALField;
            }
            set {
                if ((this.FAC_TOTALField.Equals(value) != true)) {
                    this.FAC_TOTALField = value;
                    this.RaisePropertyChanged("FAC_TOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public FrontEnd.APIDTOEmpresa.CLIENTE CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public FrontEnd.APIDTOEmpresa.DETALLE_FACTURA[] DETALLE_FACTURA {
            get {
                return this.DETALLE_FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLE_FACTURAField, value) != true)) {
                    this.DETALLE_FACTURAField = value;
                    this.RaisePropertyChanged("DETALLE_FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public FrontEnd.APIDTOEmpresa.EMPRESA EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESAField, value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLIENTE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CLIENTE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CEDULAField;
        
        private int US_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_TELEFONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CORREOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_DIRECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.USUARIO USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.FACTURA[] FACTURAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CLI_CEDULA {
            get {
                return this.CLI_CEDULAField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CEDULAField, value) != true)) {
                    this.CLI_CEDULAField = value;
                    this.RaisePropertyChanged("CLI_CEDULA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int US_COD {
            get {
                return this.US_CODField;
            }
            set {
                if ((this.US_CODField.Equals(value) != true)) {
                    this.US_CODField = value;
                    this.RaisePropertyChanged("US_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CLI_NOMBRE {
            get {
                return this.CLI_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_NOMBREField, value) != true)) {
                    this.CLI_NOMBREField = value;
                    this.RaisePropertyChanged("CLI_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CLI_TELEFONO {
            get {
                return this.CLI_TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_TELEFONOField, value) != true)) {
                    this.CLI_TELEFONOField = value;
                    this.RaisePropertyChanged("CLI_TELEFONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CLI_CORREO {
            get {
                return this.CLI_CORREOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CORREOField, value) != true)) {
                    this.CLI_CORREOField = value;
                    this.RaisePropertyChanged("CLI_CORREO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CLI_DIRECCION {
            get {
                return this.CLI_DIRECCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_DIRECCIONField, value) != true)) {
                    this.CLI_DIRECCIONField = value;
                    this.RaisePropertyChanged("CLI_DIRECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CLI_ESTADO {
            get {
                return this.CLI_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_ESTADOField, value) != true)) {
                    this.CLI_ESTADOField = value;
                    this.RaisePropertyChanged("CLI_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public FrontEnd.APIDTOEmpresa.USUARIO USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public FrontEnd.APIDTOEmpresa.FACTURA[] FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DETALLE_FACTURA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DETALLE_FACTURA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_DET_FACField;
        
        private int FAC_CODField;
        
        private int PRD_CODField;
        
        private System.Nullable<int> DTF_CANTIDADField;
        
        private System.Nullable<decimal> DTF_PRECIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DTF_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.FACTURA FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.PRODUCTO PRODUCTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_DET_FAC {
            get {
                return this.ID_DET_FACField;
            }
            set {
                if ((this.ID_DET_FACField.Equals(value) != true)) {
                    this.ID_DET_FACField = value;
                    this.RaisePropertyChanged("ID_DET_FAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int FAC_COD {
            get {
                return this.FAC_CODField;
            }
            set {
                if ((this.FAC_CODField.Equals(value) != true)) {
                    this.FAC_CODField = value;
                    this.RaisePropertyChanged("FAC_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> DTF_CANTIDAD {
            get {
                return this.DTF_CANTIDADField;
            }
            set {
                if ((this.DTF_CANTIDADField.Equals(value) != true)) {
                    this.DTF_CANTIDADField = value;
                    this.RaisePropertyChanged("DTF_CANTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> DTF_PRECIO {
            get {
                return this.DTF_PRECIOField;
            }
            set {
                if ((this.DTF_PRECIOField.Equals(value) != true)) {
                    this.DTF_PRECIOField = value;
                    this.RaisePropertyChanged("DTF_PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DTF_ESTADO {
            get {
                return this.DTF_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.DTF_ESTADOField, value) != true)) {
                    this.DTF_ESTADOField = value;
                    this.RaisePropertyChanged("DTF_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FrontEnd.APIDTOEmpresa.FACTURA FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public FrontEnd.APIDTOEmpresa.PRODUCTO PRODUCTO {
            get {
                return this.PRODUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTOField, value) != true)) {
                    this.PRODUCTOField = value;
                    this.RaisePropertyChanged("PRODUCTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int US_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_PASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_ROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.CLIENTE[] CLIENTEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int US_COD {
            get {
                return this.US_CODField;
            }
            set {
                if ((this.US_CODField.Equals(value) != true)) {
                    this.US_CODField = value;
                    this.RaisePropertyChanged("US_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string US_USUARIO {
            get {
                return this.US_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.US_USUARIOField, value) != true)) {
                    this.US_USUARIOField = value;
                    this.RaisePropertyChanged("US_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string US_PASS {
            get {
                return this.US_PASSField;
            }
            set {
                if ((object.ReferenceEquals(this.US_PASSField, value) != true)) {
                    this.US_PASSField = value;
                    this.RaisePropertyChanged("US_PASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string US_ROL {
            get {
                return this.US_ROLField;
            }
            set {
                if ((object.ReferenceEquals(this.US_ROLField, value) != true)) {
                    this.US_ROLField = value;
                    this.RaisePropertyChanged("US_ROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public FrontEnd.APIDTOEmpresa.CLIENTE[] CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PRODUCTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PRODUCTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PRD_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRD_DESCRIPCIONField;
        
        private System.Nullable<decimal> PRD_PRECIOField;
        
        private System.Nullable<int> PRD_STOCKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRD_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.DETALLE_FACTURA[] DETALLE_FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.IMAGEN[] IMAGENField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PRD_DESCRIPCION {
            get {
                return this.PRD_DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.PRD_DESCRIPCIONField, value) != true)) {
                    this.PRD_DESCRIPCIONField = value;
                    this.RaisePropertyChanged("PRD_DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> PRD_PRECIO {
            get {
                return this.PRD_PRECIOField;
            }
            set {
                if ((this.PRD_PRECIOField.Equals(value) != true)) {
                    this.PRD_PRECIOField = value;
                    this.RaisePropertyChanged("PRD_PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> PRD_STOCK {
            get {
                return this.PRD_STOCKField;
            }
            set {
                if ((this.PRD_STOCKField.Equals(value) != true)) {
                    this.PRD_STOCKField = value;
                    this.RaisePropertyChanged("PRD_STOCK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PRD_ESTADO {
            get {
                return this.PRD_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRD_ESTADOField, value) != true)) {
                    this.PRD_ESTADOField = value;
                    this.RaisePropertyChanged("PRD_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FrontEnd.APIDTOEmpresa.DETALLE_FACTURA[] DETALLE_FACTURA {
            get {
                return this.DETALLE_FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLE_FACTURAField, value) != true)) {
                    this.DETALLE_FACTURAField = value;
                    this.RaisePropertyChanged("DETALLE_FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FrontEnd.APIDTOEmpresa.IMAGEN[] IMAGEN {
            get {
                return this.IMAGENField;
            }
            set {
                if ((object.ReferenceEquals(this.IMAGENField, value) != true)) {
                    this.IMAGENField = value;
                    this.RaisePropertyChanged("IMAGEN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IMAGEN", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class IMAGEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IMG_IDField;
        
        private int PRD_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIDTOEmpresa.PRODUCTO PRODUCTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IMG_ID {
            get {
                return this.IMG_IDField;
            }
            set {
                if ((this.IMG_IDField.Equals(value) != true)) {
                    this.IMG_IDField = value;
                    this.RaisePropertyChanged("IMG_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMG_URL {
            get {
                return this.IMG_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_URLField, value) != true)) {
                    this.IMG_URLField = value;
                    this.RaisePropertyChanged("IMG_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IMG_TIPO {
            get {
                return this.IMG_TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_TIPOField, value) != true)) {
                    this.IMG_TIPOField = value;
                    this.RaisePropertyChanged("IMG_TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public FrontEnd.APIDTOEmpresa.PRODUCTO PRODUCTO {
            get {
                return this.PRODUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTOField, value) != true)) {
                    this.PRODUCTOField = value;
                    this.RaisePropertyChanged("PRODUCTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIDTOEmpresa.APIDTOEmpresaSoap")]
    public interface APIDTOEmpresaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarEmpresaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarEmpresa", ReplyAction="*")]
        FrontEnd.APIDTOEmpresa.MostrarEmpresaResponse MostrarEmpresa(FrontEnd.APIDTOEmpresa.MostrarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarEmpresa", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIDTOEmpresa.MostrarEmpresaResponse> MostrarEmpresaAsync(FrontEnd.APIDTOEmpresa.MostrarEmpresaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarEmpresa", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOEmpresa.MostrarEmpresaRequestBody Body;
        
        public MostrarEmpresaRequest() {
        }
        
        public MostrarEmpresaRequest(FrontEnd.APIDTOEmpresa.MostrarEmpresaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarEmpresaRequestBody {
        
        public MostrarEmpresaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarEmpresaResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIDTOEmpresa.MostrarEmpresaResponseBody Body;
        
        public MostrarEmpresaResponse() {
        }
        
        public MostrarEmpresaResponse(FrontEnd.APIDTOEmpresa.MostrarEmpresaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarEmpresaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIDTOEmpresa.EMPRESA[] MostrarEmpresaResult;
        
        public MostrarEmpresaResponseBody() {
        }
        
        public MostrarEmpresaResponseBody(FrontEnd.APIDTOEmpresa.EMPRESA[] MostrarEmpresaResult) {
            this.MostrarEmpresaResult = MostrarEmpresaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIDTOEmpresaSoapChannel : FrontEnd.APIDTOEmpresa.APIDTOEmpresaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIDTOEmpresaSoapClient : System.ServiceModel.ClientBase<FrontEnd.APIDTOEmpresa.APIDTOEmpresaSoap>, FrontEnd.APIDTOEmpresa.APIDTOEmpresaSoap {
        
        public APIDTOEmpresaSoapClient() {
        }
        
        public APIDTOEmpresaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIDTOEmpresaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTOEmpresaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIDTOEmpresaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIDTOEmpresa.MostrarEmpresaResponse FrontEnd.APIDTOEmpresa.APIDTOEmpresaSoap.MostrarEmpresa(FrontEnd.APIDTOEmpresa.MostrarEmpresaRequest request) {
            return base.Channel.MostrarEmpresa(request);
        }
        
        public FrontEnd.APIDTOEmpresa.EMPRESA[] MostrarEmpresa() {
            FrontEnd.APIDTOEmpresa.MostrarEmpresaRequest inValue = new FrontEnd.APIDTOEmpresa.MostrarEmpresaRequest();
            inValue.Body = new FrontEnd.APIDTOEmpresa.MostrarEmpresaRequestBody();
            FrontEnd.APIDTOEmpresa.MostrarEmpresaResponse retVal = ((FrontEnd.APIDTOEmpresa.APIDTOEmpresaSoap)(this)).MostrarEmpresa(inValue);
            return retVal.Body.MostrarEmpresaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIDTOEmpresa.MostrarEmpresaResponse> FrontEnd.APIDTOEmpresa.APIDTOEmpresaSoap.MostrarEmpresaAsync(FrontEnd.APIDTOEmpresa.MostrarEmpresaRequest request) {
            return base.Channel.MostrarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIDTOEmpresa.MostrarEmpresaResponse> MostrarEmpresaAsync() {
            FrontEnd.APIDTOEmpresa.MostrarEmpresaRequest inValue = new FrontEnd.APIDTOEmpresa.MostrarEmpresaRequest();
            inValue.Body = new FrontEnd.APIDTOEmpresa.MostrarEmpresaRequestBody();
            return ((FrontEnd.APIDTOEmpresa.APIDTOEmpresaSoap)(this)).MostrarEmpresaAsync(inValue);
        }
    }
}
