//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public decimal ID_DET_FAC { get; set; }
        public decimal FAC_COD { get; set; }
        public decimal PRD_COD { get; set; }
        public Nullable<decimal> DTF_CANTIDAD { get; set; }
        public Nullable<decimal> DTF_PRECIO { get; set; }

        public FACTURA FACTURA { get; set; }
        public PRODUCTO PRODUCTO { get; set; }
    }
}
