//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGEN
    {
        public decimal IMG_ID { get; set; }
        public decimal PRD_COD { get; set; }
        public string IMG_URL { get; set; }

        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
