//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db17842Entities2 : DbContext
    {
        public db17842Entities2()
            : base("name=db17842Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<FACTURA> FACTURA { get; set; }
        public virtual DbSet<IMAGEN> IMAGEN { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual ObjectResult<seleccionarClientesSP_Result> seleccionarClientesSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seleccionarClientesSP_Result>("seleccionarClientesSP");
        }
    
        public virtual ObjectResult<seleccionarEmpresaSP_Result> seleccionarEmpresaSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seleccionarEmpresaSP_Result>("seleccionarEmpresaSP");
        }
    
        public virtual ObjectResult<seleccionarFacturaDetalleSP_Result> seleccionarFacturaDetalleSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seleccionarFacturaDetalleSP_Result>("seleccionarFacturaDetalleSP");
        }
    
        public virtual ObjectResult<seleccionarFacturaEncabezadoSP_Result> seleccionarFacturaEncabezadoSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seleccionarFacturaEncabezadoSP_Result>("seleccionarFacturaEncabezadoSP");
        }
    
        public virtual ObjectResult<seleccionarProductosSP_Result> seleccionarProductosSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seleccionarProductosSP_Result>("seleccionarProductosSP");
        }
    
        public virtual ObjectResult<seleccionarUsuariosSP_Result> seleccionarUsuariosSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seleccionarUsuariosSP_Result>("seleccionarUsuariosSP");
        }
    }
}
