//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.APIGestionarFacturas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FACTURA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FACTURA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FAC_CODField;
        
        private int ID_EMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CEDULAField;
        
        private System.Nullable<System.DateTime> FAC_FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAC_ESTADOField;
        
        private System.Nullable<decimal> FAC_SUBTOTALField;
        
        private System.Nullable<decimal> FAC_IVAField;
        
        private System.Nullable<decimal> FAC_TOTALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.CLIENTE CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.DETALLE_FACTURA[] DETALLE_FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.EMPRESA EMPRESAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FAC_COD {
            get {
                return this.FAC_CODField;
            }
            set {
                if ((this.FAC_CODField.Equals(value) != true)) {
                    this.FAC_CODField = value;
                    this.RaisePropertyChanged("FAC_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_EMP {
            get {
                return this.ID_EMPField;
            }
            set {
                if ((this.ID_EMPField.Equals(value) != true)) {
                    this.ID_EMPField = value;
                    this.RaisePropertyChanged("ID_EMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CLI_CEDULA {
            get {
                return this.CLI_CEDULAField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CEDULAField, value) != true)) {
                    this.CLI_CEDULAField = value;
                    this.RaisePropertyChanged("CLI_CEDULA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> FAC_FECHA {
            get {
                return this.FAC_FECHAField;
            }
            set {
                if ((this.FAC_FECHAField.Equals(value) != true)) {
                    this.FAC_FECHAField = value;
                    this.RaisePropertyChanged("FAC_FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FAC_ESTADO {
            get {
                return this.FAC_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.FAC_ESTADOField, value) != true)) {
                    this.FAC_ESTADOField = value;
                    this.RaisePropertyChanged("FAC_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> FAC_SUBTOTAL {
            get {
                return this.FAC_SUBTOTALField;
            }
            set {
                if ((this.FAC_SUBTOTALField.Equals(value) != true)) {
                    this.FAC_SUBTOTALField = value;
                    this.RaisePropertyChanged("FAC_SUBTOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> FAC_IVA {
            get {
                return this.FAC_IVAField;
            }
            set {
                if ((this.FAC_IVAField.Equals(value) != true)) {
                    this.FAC_IVAField = value;
                    this.RaisePropertyChanged("FAC_IVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> FAC_TOTAL {
            get {
                return this.FAC_TOTALField;
            }
            set {
                if ((this.FAC_TOTALField.Equals(value) != true)) {
                    this.FAC_TOTALField = value;
                    this.RaisePropertyChanged("FAC_TOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public FrontEnd.APIGestionarFacturas.CLIENTE CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public FrontEnd.APIGestionarFacturas.DETALLE_FACTURA[] DETALLE_FACTURA {
            get {
                return this.DETALLE_FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLE_FACTURAField, value) != true)) {
                    this.DETALLE_FACTURAField = value;
                    this.RaisePropertyChanged("DETALLE_FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public FrontEnd.APIGestionarFacturas.EMPRESA EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESAField, value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLIENTE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CLIENTE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CEDULAField;
        
        private int US_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_TELEFONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_CORREOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_DIRECCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLI_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.USUARIO USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.FACTURA[] FACTURAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CLI_CEDULA {
            get {
                return this.CLI_CEDULAField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CEDULAField, value) != true)) {
                    this.CLI_CEDULAField = value;
                    this.RaisePropertyChanged("CLI_CEDULA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int US_COD {
            get {
                return this.US_CODField;
            }
            set {
                if ((this.US_CODField.Equals(value) != true)) {
                    this.US_CODField = value;
                    this.RaisePropertyChanged("US_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CLI_NOMBRE {
            get {
                return this.CLI_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_NOMBREField, value) != true)) {
                    this.CLI_NOMBREField = value;
                    this.RaisePropertyChanged("CLI_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CLI_TELEFONO {
            get {
                return this.CLI_TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_TELEFONOField, value) != true)) {
                    this.CLI_TELEFONOField = value;
                    this.RaisePropertyChanged("CLI_TELEFONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CLI_CORREO {
            get {
                return this.CLI_CORREOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_CORREOField, value) != true)) {
                    this.CLI_CORREOField = value;
                    this.RaisePropertyChanged("CLI_CORREO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CLI_DIRECCION {
            get {
                return this.CLI_DIRECCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_DIRECCIONField, value) != true)) {
                    this.CLI_DIRECCIONField = value;
                    this.RaisePropertyChanged("CLI_DIRECCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CLI_ESTADO {
            get {
                return this.CLI_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLI_ESTADOField, value) != true)) {
                    this.CLI_ESTADOField = value;
                    this.RaisePropertyChanged("CLI_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public FrontEnd.APIGestionarFacturas.USUARIO USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public FrontEnd.APIGestionarFacturas.FACTURA[] FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMPRESA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EMPRESA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_EMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_MISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_VISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMP_TELFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.FACTURA[] FACTURAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_EMP {
            get {
                return this.ID_EMPField;
            }
            set {
                if ((this.ID_EMPField.Equals(value) != true)) {
                    this.ID_EMPField = value;
                    this.RaisePropertyChanged("ID_EMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EMP_RUC {
            get {
                return this.EMP_RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_RUCField, value) != true)) {
                    this.EMP_RUCField = value;
                    this.RaisePropertyChanged("EMP_RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EMP_NOMBRE {
            get {
                return this.EMP_NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_NOMBREField, value) != true)) {
                    this.EMP_NOMBREField = value;
                    this.RaisePropertyChanged("EMP_NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EMP_MISION {
            get {
                return this.EMP_MISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_MISIONField, value) != true)) {
                    this.EMP_MISIONField = value;
                    this.RaisePropertyChanged("EMP_MISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EMP_VISION {
            get {
                return this.EMP_VISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_VISIONField, value) != true)) {
                    this.EMP_VISIONField = value;
                    this.RaisePropertyChanged("EMP_VISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EMP_TELF {
            get {
                return this.EMP_TELFField;
            }
            set {
                if ((object.ReferenceEquals(this.EMP_TELFField, value) != true)) {
                    this.EMP_TELFField = value;
                    this.RaisePropertyChanged("EMP_TELF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FrontEnd.APIGestionarFacturas.FACTURA[] FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DETALLE_FACTURA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DETALLE_FACTURA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_DET_FACField;
        
        private int FAC_CODField;
        
        private int PRD_CODField;
        
        private System.Nullable<int> DTF_CANTIDADField;
        
        private System.Nullable<decimal> DTF_PRECIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DTF_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.FACTURA FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.PRODUCTO PRODUCTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_DET_FAC {
            get {
                return this.ID_DET_FACField;
            }
            set {
                if ((this.ID_DET_FACField.Equals(value) != true)) {
                    this.ID_DET_FACField = value;
                    this.RaisePropertyChanged("ID_DET_FAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int FAC_COD {
            get {
                return this.FAC_CODField;
            }
            set {
                if ((this.FAC_CODField.Equals(value) != true)) {
                    this.FAC_CODField = value;
                    this.RaisePropertyChanged("FAC_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> DTF_CANTIDAD {
            get {
                return this.DTF_CANTIDADField;
            }
            set {
                if ((this.DTF_CANTIDADField.Equals(value) != true)) {
                    this.DTF_CANTIDADField = value;
                    this.RaisePropertyChanged("DTF_CANTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> DTF_PRECIO {
            get {
                return this.DTF_PRECIOField;
            }
            set {
                if ((this.DTF_PRECIOField.Equals(value) != true)) {
                    this.DTF_PRECIOField = value;
                    this.RaisePropertyChanged("DTF_PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DTF_ESTADO {
            get {
                return this.DTF_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.DTF_ESTADOField, value) != true)) {
                    this.DTF_ESTADOField = value;
                    this.RaisePropertyChanged("DTF_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FrontEnd.APIGestionarFacturas.FACTURA FACTURA {
            get {
                return this.FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTURAField, value) != true)) {
                    this.FACTURAField = value;
                    this.RaisePropertyChanged("FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public FrontEnd.APIGestionarFacturas.PRODUCTO PRODUCTO {
            get {
                return this.PRODUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTOField, value) != true)) {
                    this.PRODUCTOField = value;
                    this.RaisePropertyChanged("PRODUCTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int US_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_PASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string US_ROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.CLIENTE[] CLIENTEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int US_COD {
            get {
                return this.US_CODField;
            }
            set {
                if ((this.US_CODField.Equals(value) != true)) {
                    this.US_CODField = value;
                    this.RaisePropertyChanged("US_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string US_USUARIO {
            get {
                return this.US_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.US_USUARIOField, value) != true)) {
                    this.US_USUARIOField = value;
                    this.RaisePropertyChanged("US_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string US_PASS {
            get {
                return this.US_PASSField;
            }
            set {
                if ((object.ReferenceEquals(this.US_PASSField, value) != true)) {
                    this.US_PASSField = value;
                    this.RaisePropertyChanged("US_PASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string US_ROL {
            get {
                return this.US_ROLField;
            }
            set {
                if ((object.ReferenceEquals(this.US_ROLField, value) != true)) {
                    this.US_ROLField = value;
                    this.RaisePropertyChanged("US_ROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public FrontEnd.APIGestionarFacturas.CLIENTE[] CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PRODUCTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PRODUCTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PRD_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRD_DESCRIPCIONField;
        
        private System.Nullable<decimal> PRD_PRECIOField;
        
        private System.Nullable<int> PRD_STOCKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRD_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.DETALLE_FACTURA[] DETALLE_FACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.IMAGEN[] IMAGENField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PRD_DESCRIPCION {
            get {
                return this.PRD_DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.PRD_DESCRIPCIONField, value) != true)) {
                    this.PRD_DESCRIPCIONField = value;
                    this.RaisePropertyChanged("PRD_DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> PRD_PRECIO {
            get {
                return this.PRD_PRECIOField;
            }
            set {
                if ((this.PRD_PRECIOField.Equals(value) != true)) {
                    this.PRD_PRECIOField = value;
                    this.RaisePropertyChanged("PRD_PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> PRD_STOCK {
            get {
                return this.PRD_STOCKField;
            }
            set {
                if ((this.PRD_STOCKField.Equals(value) != true)) {
                    this.PRD_STOCKField = value;
                    this.RaisePropertyChanged("PRD_STOCK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PRD_ESTADO {
            get {
                return this.PRD_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRD_ESTADOField, value) != true)) {
                    this.PRD_ESTADOField = value;
                    this.RaisePropertyChanged("PRD_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FrontEnd.APIGestionarFacturas.DETALLE_FACTURA[] DETALLE_FACTURA {
            get {
                return this.DETALLE_FACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLE_FACTURAField, value) != true)) {
                    this.DETALLE_FACTURAField = value;
                    this.RaisePropertyChanged("DETALLE_FACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FrontEnd.APIGestionarFacturas.IMAGEN[] IMAGEN {
            get {
                return this.IMAGENField;
            }
            set {
                if ((object.ReferenceEquals(this.IMAGENField, value) != true)) {
                    this.IMAGENField = value;
                    this.RaisePropertyChanged("IMAGEN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IMAGEN", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class IMAGEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IMG_IDField;
        
        private int PRD_CODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMG_TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontEnd.APIGestionarFacturas.PRODUCTO PRODUCTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IMG_ID {
            get {
                return this.IMG_IDField;
            }
            set {
                if ((this.IMG_IDField.Equals(value) != true)) {
                    this.IMG_IDField = value;
                    this.RaisePropertyChanged("IMG_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PRD_COD {
            get {
                return this.PRD_CODField;
            }
            set {
                if ((this.PRD_CODField.Equals(value) != true)) {
                    this.PRD_CODField = value;
                    this.RaisePropertyChanged("PRD_COD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMG_URL {
            get {
                return this.IMG_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_URLField, value) != true)) {
                    this.IMG_URLField = value;
                    this.RaisePropertyChanged("IMG_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IMG_TIPO {
            get {
                return this.IMG_TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.IMG_TIPOField, value) != true)) {
                    this.IMG_TIPOField = value;
                    this.RaisePropertyChanged("IMG_TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public FrontEnd.APIGestionarFacturas.PRODUCTO PRODUCTO {
            get {
                return this.PRODUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCTOField, value) != true)) {
                    this.PRODUCTOField = value;
                    this.RaisePropertyChanged("PRODUCTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIGestionarFacturas.APIFacturasSoap")]
    public interface APIFacturasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SeleccionarFacturasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarFacturas", ReplyAction="*")]
        FrontEnd.APIGestionarFacturas.SeleccionarFacturasResponse SeleccionarFacturas(FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarFacturas", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.SeleccionarFacturasResponse> SeleccionarFacturasAsync(FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento seleccionarFacturaPorIDResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seleccionarFacturaPorID", ReplyAction="*")]
        FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDResponse seleccionarFacturaPorID(FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seleccionarFacturaPorID", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDResponse> seleccionarFacturaPorIDAsync(FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento proInsertado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarFactura", ReplyAction="*")]
        FrontEnd.APIGestionarFacturas.insertarFacturaResponse insertarFactura(FrontEnd.APIGestionarFacturas.insertarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.insertarFacturaResponse> insertarFacturaAsync(FrontEnd.APIGestionarFacturas.insertarFacturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento proActualizado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarFactura", ReplyAction="*")]
        FrontEnd.APIGestionarFacturas.actualizarFacturaResponse actualizarFactura(FrontEnd.APIGestionarFacturas.actualizarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.actualizarFacturaResponse> actualizarFacturaAsync(FrontEnd.APIGestionarFacturas.actualizarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarFactura", ReplyAction="*")]
        bool eliminarFactura(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> eliminarFacturaAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarFacturasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarFacturas", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequestBody Body;
        
        public SeleccionarFacturasRequest() {
        }
        
        public SeleccionarFacturasRequest(FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SeleccionarFacturasRequestBody {
        
        public SeleccionarFacturasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarFacturasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarFacturasResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarFacturas.SeleccionarFacturasResponseBody Body;
        
        public SeleccionarFacturasResponse() {
        }
        
        public SeleccionarFacturasResponse(FrontEnd.APIGestionarFacturas.SeleccionarFacturasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarFacturasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarFacturas.FACTURA[] SeleccionarFacturasResult;
        
        public SeleccionarFacturasResponseBody() {
        }
        
        public SeleccionarFacturasResponseBody(FrontEnd.APIGestionarFacturas.FACTURA[] SeleccionarFacturasResult) {
            this.SeleccionarFacturasResult = SeleccionarFacturasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seleccionarFacturaPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seleccionarFacturaPorID", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequestBody Body;
        
        public seleccionarFacturaPorIDRequest() {
        }
        
        public seleccionarFacturaPorIDRequest(FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seleccionarFacturaPorIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigo;
        
        public seleccionarFacturaPorIDRequestBody() {
        }
        
        public seleccionarFacturaPorIDRequestBody(int codigo) {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seleccionarFacturaPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seleccionarFacturaPorIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDResponseBody Body;
        
        public seleccionarFacturaPorIDResponse() {
        }
        
        public seleccionarFacturaPorIDResponse(FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seleccionarFacturaPorIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarFacturas.FACTURA seleccionarFacturaPorIDResult;
        
        public seleccionarFacturaPorIDResponseBody() {
        }
        
        public seleccionarFacturaPorIDResponseBody(FrontEnd.APIGestionarFacturas.FACTURA seleccionarFacturaPorIDResult) {
            this.seleccionarFacturaPorIDResult = seleccionarFacturaPorIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarFactura", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarFacturas.insertarFacturaRequestBody Body;
        
        public insertarFacturaRequest() {
        }
        
        public insertarFacturaRequest(FrontEnd.APIGestionarFacturas.insertarFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarFacturas.FACTURA proInsertado;
        
        public insertarFacturaRequestBody() {
        }
        
        public insertarFacturaRequestBody(FrontEnd.APIGestionarFacturas.FACTURA proInsertado) {
            this.proInsertado = proInsertado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarFacturas.insertarFacturaResponseBody Body;
        
        public insertarFacturaResponse() {
        }
        
        public insertarFacturaResponse(FrontEnd.APIGestionarFacturas.insertarFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int insertarFacturaResult;
        
        public insertarFacturaResponseBody() {
        }
        
        public insertarFacturaResponseBody(int insertarFacturaResult) {
            this.insertarFacturaResult = insertarFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarFactura", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarFacturas.actualizarFacturaRequestBody Body;
        
        public actualizarFacturaRequest() {
        }
        
        public actualizarFacturaRequest(FrontEnd.APIGestionarFacturas.actualizarFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.APIGestionarFacturas.FACTURA proActualizado;
        
        public actualizarFacturaRequestBody() {
        }
        
        public actualizarFacturaRequestBody(FrontEnd.APIGestionarFacturas.FACTURA proActualizado) {
            this.proActualizado = proActualizado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.APIGestionarFacturas.actualizarFacturaResponseBody Body;
        
        public actualizarFacturaResponse() {
        }
        
        public actualizarFacturaResponse(FrontEnd.APIGestionarFacturas.actualizarFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool actualizarFacturaResult;
        
        public actualizarFacturaResponseBody() {
        }
        
        public actualizarFacturaResponseBody(bool actualizarFacturaResult) {
            this.actualizarFacturaResult = actualizarFacturaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIFacturasSoapChannel : FrontEnd.APIGestionarFacturas.APIFacturasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIFacturasSoapClient : System.ServiceModel.ClientBase<FrontEnd.APIGestionarFacturas.APIFacturasSoap>, FrontEnd.APIGestionarFacturas.APIFacturasSoap {
        
        public APIFacturasSoapClient() {
        }
        
        public APIFacturasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIFacturasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIFacturasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIFacturasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarFacturas.SeleccionarFacturasResponse FrontEnd.APIGestionarFacturas.APIFacturasSoap.SeleccionarFacturas(FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequest request) {
            return base.Channel.SeleccionarFacturas(request);
        }
        
        public FrontEnd.APIGestionarFacturas.FACTURA[] SeleccionarFacturas() {
            FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequest inValue = new FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequest();
            inValue.Body = new FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequestBody();
            FrontEnd.APIGestionarFacturas.SeleccionarFacturasResponse retVal = ((FrontEnd.APIGestionarFacturas.APIFacturasSoap)(this)).SeleccionarFacturas(inValue);
            return retVal.Body.SeleccionarFacturasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.SeleccionarFacturasResponse> FrontEnd.APIGestionarFacturas.APIFacturasSoap.SeleccionarFacturasAsync(FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequest request) {
            return base.Channel.SeleccionarFacturasAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.SeleccionarFacturasResponse> SeleccionarFacturasAsync() {
            FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequest inValue = new FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequest();
            inValue.Body = new FrontEnd.APIGestionarFacturas.SeleccionarFacturasRequestBody();
            return ((FrontEnd.APIGestionarFacturas.APIFacturasSoap)(this)).SeleccionarFacturasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDResponse FrontEnd.APIGestionarFacturas.APIFacturasSoap.seleccionarFacturaPorID(FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequest request) {
            return base.Channel.seleccionarFacturaPorID(request);
        }
        
        public FrontEnd.APIGestionarFacturas.FACTURA seleccionarFacturaPorID(int codigo) {
            FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequest inValue = new FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequest();
            inValue.Body = new FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequestBody();
            inValue.Body.codigo = codigo;
            FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDResponse retVal = ((FrontEnd.APIGestionarFacturas.APIFacturasSoap)(this)).seleccionarFacturaPorID(inValue);
            return retVal.Body.seleccionarFacturaPorIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDResponse> FrontEnd.APIGestionarFacturas.APIFacturasSoap.seleccionarFacturaPorIDAsync(FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequest request) {
            return base.Channel.seleccionarFacturaPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDResponse> seleccionarFacturaPorIDAsync(int codigo) {
            FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequest inValue = new FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequest();
            inValue.Body = new FrontEnd.APIGestionarFacturas.seleccionarFacturaPorIDRequestBody();
            inValue.Body.codigo = codigo;
            return ((FrontEnd.APIGestionarFacturas.APIFacturasSoap)(this)).seleccionarFacturaPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarFacturas.insertarFacturaResponse FrontEnd.APIGestionarFacturas.APIFacturasSoap.insertarFactura(FrontEnd.APIGestionarFacturas.insertarFacturaRequest request) {
            return base.Channel.insertarFactura(request);
        }
        
        public int insertarFactura(FrontEnd.APIGestionarFacturas.FACTURA proInsertado) {
            FrontEnd.APIGestionarFacturas.insertarFacturaRequest inValue = new FrontEnd.APIGestionarFacturas.insertarFacturaRequest();
            inValue.Body = new FrontEnd.APIGestionarFacturas.insertarFacturaRequestBody();
            inValue.Body.proInsertado = proInsertado;
            FrontEnd.APIGestionarFacturas.insertarFacturaResponse retVal = ((FrontEnd.APIGestionarFacturas.APIFacturasSoap)(this)).insertarFactura(inValue);
            return retVal.Body.insertarFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.insertarFacturaResponse> FrontEnd.APIGestionarFacturas.APIFacturasSoap.insertarFacturaAsync(FrontEnd.APIGestionarFacturas.insertarFacturaRequest request) {
            return base.Channel.insertarFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.insertarFacturaResponse> insertarFacturaAsync(FrontEnd.APIGestionarFacturas.FACTURA proInsertado) {
            FrontEnd.APIGestionarFacturas.insertarFacturaRequest inValue = new FrontEnd.APIGestionarFacturas.insertarFacturaRequest();
            inValue.Body = new FrontEnd.APIGestionarFacturas.insertarFacturaRequestBody();
            inValue.Body.proInsertado = proInsertado;
            return ((FrontEnd.APIGestionarFacturas.APIFacturasSoap)(this)).insertarFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.APIGestionarFacturas.actualizarFacturaResponse FrontEnd.APIGestionarFacturas.APIFacturasSoap.actualizarFactura(FrontEnd.APIGestionarFacturas.actualizarFacturaRequest request) {
            return base.Channel.actualizarFactura(request);
        }
        
        public bool actualizarFactura(FrontEnd.APIGestionarFacturas.FACTURA proActualizado) {
            FrontEnd.APIGestionarFacturas.actualizarFacturaRequest inValue = new FrontEnd.APIGestionarFacturas.actualizarFacturaRequest();
            inValue.Body = new FrontEnd.APIGestionarFacturas.actualizarFacturaRequestBody();
            inValue.Body.proActualizado = proActualizado;
            FrontEnd.APIGestionarFacturas.actualizarFacturaResponse retVal = ((FrontEnd.APIGestionarFacturas.APIFacturasSoap)(this)).actualizarFactura(inValue);
            return retVal.Body.actualizarFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.actualizarFacturaResponse> FrontEnd.APIGestionarFacturas.APIFacturasSoap.actualizarFacturaAsync(FrontEnd.APIGestionarFacturas.actualizarFacturaRequest request) {
            return base.Channel.actualizarFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.APIGestionarFacturas.actualizarFacturaResponse> actualizarFacturaAsync(FrontEnd.APIGestionarFacturas.FACTURA proActualizado) {
            FrontEnd.APIGestionarFacturas.actualizarFacturaRequest inValue = new FrontEnd.APIGestionarFacturas.actualizarFacturaRequest();
            inValue.Body = new FrontEnd.APIGestionarFacturas.actualizarFacturaRequestBody();
            inValue.Body.proActualizado = proActualizado;
            return ((FrontEnd.APIGestionarFacturas.APIFacturasSoap)(this)).actualizarFacturaAsync(inValue);
        }
        
        public bool eliminarFactura(int id) {
            return base.Channel.eliminarFactura(id);
        }
        
        public System.Threading.Tasks.Task<bool> eliminarFacturaAsync(int id) {
            return base.Channel.eliminarFacturaAsync(id);
        }
    }
}
